/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ActionField.
* @enum {}
* @readonly
*/
export default class ActionField {
    
        /**
         * value: 0
         * @const
         */
        "SignDocument" = 0;

    
        /**
         * value: 1
         * @const
         */
        "ViewDocument" = 1;

    
        /**
         * value: 2
         * @const
         */
        "ApproveDocument" = 2;

    

    /**
    * Returns a <code>ActionField</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ActionField} The enum <code>ActionField</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

