/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AdvancedFieldType.
* @enum {}
* @readonly
*/
export default class AdvancedFieldType {
    
        /**
         * value: 0
         * @const
         */
        "DropDown" = 0;

    
        /**
         * value: 1
         * @const
         */
        "CheckBoxGroup" = 1;

    
        /**
         * value: 2
         * @const
         */
        "OptionalDropDown" = 2;

    
        /**
         * value: 3
         * @const
         */
        "RadioGroup" = 3;

    
        /**
         * value: 4
         * @const
         */
        "DateMand" = 4;

    
        /**
         * value: 5
         * @const
         */
        "DateOpt" = 5;

    
        /**
         * value: 6
         * @const
         */
        "DropDownCountry" = 6;

    
        /**
         * value: 7
         * @const
         */
        "OptionalDropDownCountry" = 7;

    
        /**
         * value: 8
         * @const
         */
        "DropDownMobilePrefix" = 8;

    
        /**
         * value: 9
         * @const
         */
        "OptionalDropDownMobilePrefix" = 9;

    

    /**
    * Returns a <code>AdvancedFieldType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AdvancedFieldType} The enum <code>AdvancedFieldType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

