/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatePortfolioResponse model module.
 * @module model/CreatePortfolioResponse
 * @version 1.0.1
 */
class CreatePortfolioResponse {
    /**
     * Constructs a new <code>CreatePortfolioResponse</code>.
     * #### The response received after a portfolio is created.
     * @alias module:model/CreatePortfolioResponse
     * @param portfolioIDField {Number} Document portfolio ID field.
     * @param resultField {String} Displays the result of the call.
     */
    constructor(portfolioIDField, resultField) { 
        
        CreatePortfolioResponse.initialize(this, portfolioIDField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, portfolioIDField, resultField) { 
        obj['PortfolioIDField'] = portfolioIDField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>CreatePortfolioResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePortfolioResponse} obj Optional instance to populate.
     * @return {module:model/CreatePortfolioResponse} The populated <code>CreatePortfolioResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePortfolioResponse();

            if (data.hasOwnProperty('PortfolioIDField')) {
                obj['PortfolioIDField'] = ApiClient.convertToType(data['PortfolioIDField'], 'Number');
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Document portfolio ID field.
 * @member {Number} PortfolioIDField
 */
CreatePortfolioResponse.prototype['PortfolioIDField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
CreatePortfolioResponse.prototype['ResultField'] = undefined;






export default CreatePortfolioResponse;

