/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The CreatePortfolioRequest model module.
 * @module model/CreatePortfolioRequest
 * @version 1.0.1
 */
class CreatePortfolioRequest {
    /**
     * Constructs a new <code>CreatePortfolioRequest</code>.
     * #### Used to create a portfolio.
     * @alias module:model/CreatePortfolioRequest
     * @param docIDField {Number} Document ID field.
     * @param portfolioNameField {String} Portfolio name displayed in SigniFlow
     * @param tokenIDField {module:model/TokenField} 
     */
    constructor(docIDField, portfolioNameField, tokenIDField) { 
        
        CreatePortfolioRequest.initialize(this, docIDField, portfolioNameField, tokenIDField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, portfolioNameField, tokenIDField) { 
        obj['DocIDField'] = docIDField;
        obj['PortfolioNameField'] = portfolioNameField;
        obj['TokenIDField'] = tokenIDField;
    }

    /**
     * Constructs a <code>CreatePortfolioRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePortfolioRequest} obj Optional instance to populate.
     * @return {module:model/CreatePortfolioRequest} The populated <code>CreatePortfolioRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePortfolioRequest();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'Number');
            }
            if (data.hasOwnProperty('PortfolioNameField')) {
                obj['PortfolioNameField'] = ApiClient.convertToType(data['PortfolioNameField'], 'String');
            }
            if (data.hasOwnProperty('TokenIDField')) {
                obj['TokenIDField'] = TokenField.constructFromObject(data['TokenIDField']);
            }
        }
        return obj;
    }


}

/**
 * Document ID field.
 * @member {Number} DocIDField
 */
CreatePortfolioRequest.prototype['DocIDField'] = undefined;

/**
 * Portfolio name displayed in SigniFlow
 * @member {String} PortfolioNameField
 */
CreatePortfolioRequest.prototype['PortfolioNameField'] = undefined;

/**
 * @member {module:model/TokenField} TokenIDField
 */
CreatePortfolioRequest.prototype['TokenIDField'] = undefined;






export default CreatePortfolioRequest;

