/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DocExtension.
* @enum {}
* @readonly
*/
export default class DocExtension {
    
        /**
         * value: 0
         * @const
         */
        "pdf" = 0;

    
        /**
         * value: 1
         * @const
         */
        "xls" = 1;

    
        /**
         * value: 2
         * @const
         */
        "txt" = 2;

    
        /**
         * value: 3
         * @const
         */
        "xlsx" = 3;

    
        /**
         * value: 4
         * @const
         */
        "docx" = 4;

    
        /**
         * value: 5
         * @const
         */
        "doc" = 5;

    
        /**
         * value: 6
         * @const
         */
        "xml" = 6;

    
        /**
         * value: 7
         * @const
         */
        "png" = 7;

    
        /**
         * value: 8
         * @const
         */
        "jpg" = 8;

    
        /**
         * value: 9
         * @const
         */
        "gif" = 9;

    

    /**
    * Returns a <code>DocExtension</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DocExtension} The enum <code>DocExtension</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

