/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FieldType from './FieldType';

/**
 * The DocPrepperAddFieldsFlowIDResponse model module.
 * @module model/DocPrepperAddFieldsFlowIDResponse
 * @version 1.0.1
 */
class DocPrepperAddFieldsFlowIDResponse {
    /**
     * Constructs a new <code>DocPrepperAddFieldsFlowIDResponse</code>.
     * #### The response retuenrd when fields are added to a document using a FlowID.
     * @alias module:model/DocPrepperAddFieldsFlowIDResponse
     * @param docIDField {Number} Document ID.
     * @param fieldTypeField {module:model/FieldType} 
     * @param heightField {String} The height of the field.
     * @param pageNumberField {Number} Field page number.
     * @param prepperFieldIDField {Number} Document prepper field ID.
     * @param resultField {String} Displays the result of the call.
     * @param userIDField {Number} SigniFlow User ID
     * @param widthField {String} The width of the field.
     * @param xCoordinateField {String} X-coordinates of the field.
     * @param yCoordinateField {String} Y-coordinates of the field.
     */
    constructor(docIDField, fieldTypeField, heightField, pageNumberField, prepperFieldIDField, resultField, userIDField, widthField, xCoordinateField, yCoordinateField) { 
        
        DocPrepperAddFieldsFlowIDResponse.initialize(this, docIDField, fieldTypeField, heightField, pageNumberField, prepperFieldIDField, resultField, userIDField, widthField, xCoordinateField, yCoordinateField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, fieldTypeField, heightField, pageNumberField, prepperFieldIDField, resultField, userIDField, widthField, xCoordinateField, yCoordinateField) { 
        obj['DocIDField'] = docIDField;
        obj['FieldTypeField'] = fieldTypeField;
        obj['HeightField'] = heightField;
        obj['PageNumberField'] = pageNumberField;
        obj['PrepperFieldIDField'] = prepperFieldIDField;
        obj['ResultField'] = resultField;
        obj['UserIDField'] = userIDField;
        obj['WidthField'] = widthField;
        obj['XCoordinateField'] = xCoordinateField;
        obj['YCoordinateField'] = yCoordinateField;
    }

    /**
     * Constructs a <code>DocPrepperAddFieldsFlowIDResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocPrepperAddFieldsFlowIDResponse} obj Optional instance to populate.
     * @return {module:model/DocPrepperAddFieldsFlowIDResponse} The populated <code>DocPrepperAddFieldsFlowIDResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocPrepperAddFieldsFlowIDResponse();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'Number');
            }
            if (data.hasOwnProperty('FieldTypeField')) {
                obj['FieldTypeField'] = FieldType.constructFromObject(data['FieldTypeField']);
            }
            if (data.hasOwnProperty('HeightField')) {
                obj['HeightField'] = ApiClient.convertToType(data['HeightField'], 'String');
            }
            if (data.hasOwnProperty('PageNumberField')) {
                obj['PageNumberField'] = ApiClient.convertToType(data['PageNumberField'], 'Number');
            }
            if (data.hasOwnProperty('PrepperFieldIDField')) {
                obj['PrepperFieldIDField'] = ApiClient.convertToType(data['PrepperFieldIDField'], 'Number');
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
            if (data.hasOwnProperty('UserIDField')) {
                obj['UserIDField'] = ApiClient.convertToType(data['UserIDField'], 'Number');
            }
            if (data.hasOwnProperty('WidthField')) {
                obj['WidthField'] = ApiClient.convertToType(data['WidthField'], 'String');
            }
            if (data.hasOwnProperty('XCoordinateField')) {
                obj['XCoordinateField'] = ApiClient.convertToType(data['XCoordinateField'], 'String');
            }
            if (data.hasOwnProperty('YCoordinateField')) {
                obj['YCoordinateField'] = ApiClient.convertToType(data['YCoordinateField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Document ID.
 * @member {Number} DocIDField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['DocIDField'] = undefined;

/**
 * @member {module:model/FieldType} FieldTypeField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['FieldTypeField'] = undefined;

/**
 * The height of the field.
 * @member {String} HeightField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['HeightField'] = undefined;

/**
 * Field page number.
 * @member {Number} PageNumberField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['PageNumberField'] = undefined;

/**
 * Document prepper field ID.
 * @member {Number} PrepperFieldIDField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['PrepperFieldIDField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['ResultField'] = undefined;

/**
 * SigniFlow User ID
 * @member {Number} UserIDField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['UserIDField'] = undefined;

/**
 * The width of the field.
 * @member {String} WidthField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['WidthField'] = undefined;

/**
 * X-coordinates of the field.
 * @member {String} XCoordinateField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['XCoordinateField'] = undefined;

/**
 * Y-coordinates of the field.
 * @member {String} YCoordinateField
 */
DocPrepperAddFieldsFlowIDResponse.prototype['YCoordinateField'] = undefined;






export default DocPrepperAddFieldsFlowIDResponse;

