/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdvancedFieldType from './AdvancedFieldType';
import DocPrepperAddAdvancedFieldsRequestFieldOptionsListField from './DocPrepperAddAdvancedFieldsRequestFieldOptionsListField';

/**
 * The DocPrepperAddAdvancedFieldsRequestFieldInfoListField model module.
 * @module model/DocPrepperAddAdvancedFieldsRequestFieldInfoListField
 * @version 1.0.1
 */
class DocPrepperAddAdvancedFieldsRequestFieldInfoListField {
    /**
     * Constructs a new <code>DocPrepperAddAdvancedFieldsRequestFieldInfoListField</code>.
     * @alias module:model/DocPrepperAddAdvancedFieldsRequestFieldInfoListField
     * @param advancedFieldTypeField {module:model/AdvancedFieldType} 
     * @param docIDField {Number} Document ID field.
     * @param flowIDField {Number} Document Flow ID field.
     * @param fontFamilyField {String} Font family of the text in the field
     * @param fontSizeField {Number} Font size of the text in the field
     * @param heightField {String} Field height
     * @param widthField {String} Field Width
     * @param linkToField {String} 
     * @param nameField {String} 
     * @param pageNumberField {Number} Field page number.
     * @param searchableField {Boolean} 
     * @param userEmailField {String} User email address.
     * @param valueField {String} 
     * @param xCoordinateField {String} X-coordinates of field on the page
     * @param yCoordinateField {String} Y-coordinates of field on the page
     */
    constructor(advancedFieldTypeField, docIDField, flowIDField, fontFamilyField, fontSizeField, heightField, widthField, linkToField, nameField, pageNumberField, searchableField, userEmailField, valueField, xCoordinateField, yCoordinateField) { 
        
        DocPrepperAddAdvancedFieldsRequestFieldInfoListField.initialize(this, advancedFieldTypeField, docIDField, flowIDField, fontFamilyField, fontSizeField, heightField, widthField, linkToField, nameField, pageNumberField, searchableField, userEmailField, valueField, xCoordinateField, yCoordinateField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, advancedFieldTypeField, docIDField, flowIDField, fontFamilyField, fontSizeField, heightField, widthField, linkToField, nameField, pageNumberField, searchableField, userEmailField, valueField, xCoordinateField, yCoordinateField) { 
        obj['AdvancedFieldTypeField'] = advancedFieldTypeField;
        obj['DocIDField'] = docIDField;
        obj['FlowIDField'] = flowIDField;
        obj['FontFamilyField'] = fontFamilyField;
        obj['FontSizeField'] = fontSizeField;
        obj['HeightField'] = heightField;
        obj['WidthField'] = widthField;
        obj['LinkToField'] = linkToField;
        obj['NameField'] = nameField;
        obj['PageNumberField'] = pageNumberField;
        obj['SearchableField'] = searchableField;
        obj['UserEmailField'] = userEmailField;
        obj['ValueField'] = valueField;
        obj['XCoordinateField'] = xCoordinateField;
        obj['YCoordinateField'] = yCoordinateField;
    }

    /**
     * Constructs a <code>DocPrepperAddAdvancedFieldsRequestFieldInfoListField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocPrepperAddAdvancedFieldsRequestFieldInfoListField} obj Optional instance to populate.
     * @return {module:model/DocPrepperAddAdvancedFieldsRequestFieldInfoListField} The populated <code>DocPrepperAddAdvancedFieldsRequestFieldInfoListField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocPrepperAddAdvancedFieldsRequestFieldInfoListField();

            if (data.hasOwnProperty('AdvancedFieldTypeField')) {
                obj['AdvancedFieldTypeField'] = AdvancedFieldType.constructFromObject(data['AdvancedFieldTypeField']);
            }
            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'Number');
            }
            if (data.hasOwnProperty('FieldOptionsListField')) {
                obj['FieldOptionsListField'] = ApiClient.convertToType(data['FieldOptionsListField'], [DocPrepperAddAdvancedFieldsRequestFieldOptionsListField]);
            }
            if (data.hasOwnProperty('FlowIDField')) {
                obj['FlowIDField'] = ApiClient.convertToType(data['FlowIDField'], 'Number');
            }
            if (data.hasOwnProperty('FontFamilyField')) {
                obj['FontFamilyField'] = ApiClient.convertToType(data['FontFamilyField'], 'String');
            }
            if (data.hasOwnProperty('FontSizeField')) {
                obj['FontSizeField'] = ApiClient.convertToType(data['FontSizeField'], 'Number');
            }
            if (data.hasOwnProperty('HeightField')) {
                obj['HeightField'] = ApiClient.convertToType(data['HeightField'], 'String');
            }
            if (data.hasOwnProperty('WidthField')) {
                obj['WidthField'] = ApiClient.convertToType(data['WidthField'], 'String');
            }
            if (data.hasOwnProperty('LinkToField')) {
                obj['LinkToField'] = ApiClient.convertToType(data['LinkToField'], 'String');
            }
            if (data.hasOwnProperty('NameField')) {
                obj['NameField'] = ApiClient.convertToType(data['NameField'], 'String');
            }
            if (data.hasOwnProperty('PageNumberField')) {
                obj['PageNumberField'] = ApiClient.convertToType(data['PageNumberField'], 'Number');
            }
            if (data.hasOwnProperty('SearchableField')) {
                obj['SearchableField'] = ApiClient.convertToType(data['SearchableField'], 'Boolean');
            }
            if (data.hasOwnProperty('UserEmailField')) {
                obj['UserEmailField'] = ApiClient.convertToType(data['UserEmailField'], 'String');
            }
            if (data.hasOwnProperty('ValueField')) {
                obj['ValueField'] = ApiClient.convertToType(data['ValueField'], 'String');
            }
            if (data.hasOwnProperty('XCoordinateField')) {
                obj['XCoordinateField'] = ApiClient.convertToType(data['XCoordinateField'], 'String');
            }
            if (data.hasOwnProperty('YCoordinateField')) {
                obj['YCoordinateField'] = ApiClient.convertToType(data['YCoordinateField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AdvancedFieldType} AdvancedFieldTypeField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['AdvancedFieldTypeField'] = undefined;

/**
 * Document ID field.
 * @member {Number} DocIDField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['DocIDField'] = undefined;

/**
 * @member {Array.<module:model/DocPrepperAddAdvancedFieldsRequestFieldOptionsListField>} FieldOptionsListField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['FieldOptionsListField'] = undefined;

/**
 * Document Flow ID field.
 * @member {Number} FlowIDField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['FlowIDField'] = undefined;

/**
 * Font family of the text in the field
 * @member {String} FontFamilyField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['FontFamilyField'] = undefined;

/**
 * Font size of the text in the field
 * @member {Number} FontSizeField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['FontSizeField'] = undefined;

/**
 * Field height
 * @member {String} HeightField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['HeightField'] = undefined;

/**
 * Field Width
 * @member {String} WidthField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['WidthField'] = undefined;

/**
 * @member {String} LinkToField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['LinkToField'] = undefined;

/**
 * @member {String} NameField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['NameField'] = undefined;

/**
 * Field page number.
 * @member {Number} PageNumberField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['PageNumberField'] = undefined;

/**
 * @member {Boolean} SearchableField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['SearchableField'] = undefined;

/**
 * User email address.
 * @member {String} UserEmailField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['UserEmailField'] = undefined;

/**
 * @member {String} ValueField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['ValueField'] = undefined;

/**
 * X-coordinates of field on the page
 * @member {String} XCoordinateField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['XCoordinateField'] = undefined;

/**
 * Y-coordinates of field on the page
 * @member {String} YCoordinateField
 */
DocPrepperAddAdvancedFieldsRequestFieldInfoListField.prototype['YCoordinateField'] = undefined;






export default DocPrepperAddAdvancedFieldsRequestFieldInfoListField;

