/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DownloadPortfolioResponse model module.
 * @module model/DownloadPortfolioResponse
 * @version 1.0.1
 */
class DownloadPortfolioResponse {
    /**
     * Constructs a new <code>DownloadPortfolioResponse</code>.
     * #### The response returned when a user wants to download a portfolio.
     * @alias module:model/DownloadPortfolioResponse
     * @param portfolioDataField {String} Portfolio data field.
     * @param portfolioIDField {Number} Portfolio ID.
     * @param portfolioNameField {String} Portfolio name.
     * @param resultField {String} Displays the result of the call.
     */
    constructor(portfolioDataField, portfolioIDField, portfolioNameField, resultField) { 
        
        DownloadPortfolioResponse.initialize(this, portfolioDataField, portfolioIDField, portfolioNameField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, portfolioDataField, portfolioIDField, portfolioNameField, resultField) { 
        obj['PortfolioDataField'] = portfolioDataField;
        obj['PortfolioIDField'] = portfolioIDField;
        obj['PortfolioNameField'] = portfolioNameField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>DownloadPortfolioResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DownloadPortfolioResponse} obj Optional instance to populate.
     * @return {module:model/DownloadPortfolioResponse} The populated <code>DownloadPortfolioResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DownloadPortfolioResponse();

            if (data.hasOwnProperty('PortfolioDataField')) {
                obj['PortfolioDataField'] = ApiClient.convertToType(data['PortfolioDataField'], 'String');
            }
            if (data.hasOwnProperty('PortfolioIDField')) {
                obj['PortfolioIDField'] = ApiClient.convertToType(data['PortfolioIDField'], 'Number');
            }
            if (data.hasOwnProperty('PortfolioNameField')) {
                obj['PortfolioNameField'] = ApiClient.convertToType(data['PortfolioNameField'], 'String');
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Portfolio data field.
 * @member {String} PortfolioDataField
 */
DownloadPortfolioResponse.prototype['PortfolioDataField'] = undefined;

/**
 * Portfolio ID.
 * @member {Number} PortfolioIDField
 */
DownloadPortfolioResponse.prototype['PortfolioIDField'] = undefined;

/**
 * Portfolio name.
 * @member {String} PortfolioNameField
 */
DownloadPortfolioResponse.prototype['PortfolioNameField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
DownloadPortfolioResponse.prototype['ResultField'] = undefined;






export default DownloadPortfolioResponse;

