/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The DownloadPortfolioRequest model module.
 * @module model/DownloadPortfolioRequest
 * @version 1.0.1
 */
class DownloadPortfolioRequest {
    /**
     * Constructs a new <code>DownloadPortfolioRequest</code>.
     * #### The request sent when a user wants to download a portfolio.
     * @alias module:model/DownloadPortfolioRequest
     * @param portfolioIDField {Number} Portfolio ID.
     * @param tokenField {module:model/TokenField} 
     */
    constructor(portfolioIDField, tokenField) { 
        
        DownloadPortfolioRequest.initialize(this, portfolioIDField, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, portfolioIDField, tokenField) { 
        obj['PortfolioIDField'] = portfolioIDField;
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>DownloadPortfolioRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DownloadPortfolioRequest} obj Optional instance to populate.
     * @return {module:model/DownloadPortfolioRequest} The populated <code>DownloadPortfolioRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DownloadPortfolioRequest();

            if (data.hasOwnProperty('PortfolioIDField')) {
                obj['PortfolioIDField'] = ApiClient.convertToType(data['PortfolioIDField'], 'Number');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
        }
        return obj;
    }


}

/**
 * Portfolio ID.
 * @member {Number} PortfolioIDField
 */
DownloadPortfolioRequest.prototype['PortfolioIDField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
DownloadPortfolioRequest.prototype['TokenField'] = undefined;






export default DownloadPortfolioRequest;

