/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FieldType.
* @enum {}
* @readonly
*/
export default class FieldType {
    
        /**
         * value: 0
         * @const
         */
        "Signature" = 0;

    
        /**
         * value: 1
         * @const
         */
        "NameText" = 1;

    
        /**
         * value: 2
         * @const
         */
        "DateText" = 2;

    
        /**
         * value: 3
         * @const
         */
        "EmailAddressText" = 3;

    
        /**
         * value: 4
         * @const
         */
        "ContactNumberText" = 4;

    
        /**
         * value: 5
         * @const
         */
        "PlainText" = 5;

    
        /**
         * value: 6
         * @const
         */
        "PlainTextOptional" = 6;

    
        /**
         * value: 7
         * @const
         */
        "FaceToface" = 7;

    
        /**
         * value: 8
         * @const
         */
        "Initial" = 8;

    
        /**
         * value: 9
         * @const
         */
        "CheckBox" = 9;

    
        /**
         * value: 10
         * @const
         */
        "F2FInitial" = 10;

    
        /**
         * value: 11
         * @const
         */
        "AddressText" = 11;

    
        /**
         * value: 12
         * @const
         */
        "CompanyNameText" = 12;

    
        /**
         * value: 13
         * @const
         */
        "OptionalCurrencyText" = 13;

    
        /**
         * value: 14
         * @const
         */
        "ReadOnlyText" = 14;

    
        /**
         * value: 15
         * @const
         */
        "NumericFieldOpt" = 15;

    
        /**
         * value: 16
         * @const
         */
        "NumericFieldMand" = 16;

    
        /**
         * value: 17
         * @const
         */
        "EmailInputOptional" = 17;

    
        /**
         * value: 18
         * @const
         */
        "EmailInput" = 18;

    
        /**
         * value: 19
         * @const
         */
        "19" = 19;

    

    /**
    * Returns a <code>FieldType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/FieldType} The enum <code>FieldType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

