/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AutoRemind from './AutoRemind';
import DocExtension from './DocExtension';
import FullWorkflowRequestPortfolioInformationField from './FullWorkflowRequestPortfolioInformationField';
import FullWorkflowRequestWorkflowUsersListField from './FullWorkflowRequestWorkflowUsersListField';
import TokenField from './TokenField';

/**
 * The FullWorkflowRequest model module.
 * @module model/FullWorkflowRequest
 * @version 1.0.1
 */
class FullWorkflowRequest {
    /**
     * Constructs a new <code>FullWorkflowRequest</code>.
     * #### Request a fullworkflow of a document.
     * @alias module:model/FullWorkflowRequest
     * @param additionalDataField {String} Additional data.
     * @param autoRemindField {module:model/AutoRemind} 
     * @param customMessageField {String} Custom message.
     * @param docField {String} Document field.
     * @param docNameField {String} Document name.
     * @param dueDateField {String} Document due date.
     * @param extensionField {module:model/DocExtension} 
     * @param flattenDocumentField {Boolean} Flatten document.
     * @param keepContentSecurityField {Boolean} Keep content security.
     * @param keepCustomPropertiesField {Boolean} Keep custom properties.
     * @param keepXMPMetadataField {Boolean} Keep XMP meta data.
     * @param portfolioInformationField {module:model/FullWorkflowRequestPortfolioInformationField} 
     * @param priorityField {Number} Document priority.
     * @param sLAField {Number} SLA
     * @param sendFirstEmailField {Boolean} Confirm first user email notification will or will not be sent.
     * @param sendWorkflowEmailsField {Boolean} Confirm that workflow emails will or will not be sent.
     * @param tokenField {module:model/TokenField} 
     * @param workflowUsersListField {Array.<module:model/FullWorkflowRequestWorkflowUsersListField>} List of users in the workflow.
     */
    constructor(additionalDataField, autoRemindField, customMessageField, docField, docNameField, dueDateField, extensionField, flattenDocumentField, keepContentSecurityField, keepCustomPropertiesField, keepXMPMetadataField, portfolioInformationField, priorityField, sLAField, sendFirstEmailField, sendWorkflowEmailsField, tokenField, workflowUsersListField) { 
        
        FullWorkflowRequest.initialize(this, additionalDataField, autoRemindField, customMessageField, docField, docNameField, dueDateField, extensionField, flattenDocumentField, keepContentSecurityField, keepCustomPropertiesField, keepXMPMetadataField, portfolioInformationField, priorityField, sLAField, sendFirstEmailField, sendWorkflowEmailsField, tokenField, workflowUsersListField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, additionalDataField, autoRemindField, customMessageField, docField, docNameField, dueDateField, extensionField, flattenDocumentField, keepContentSecurityField, keepCustomPropertiesField, keepXMPMetadataField, portfolioInformationField, priorityField, sLAField, sendFirstEmailField, sendWorkflowEmailsField, tokenField, workflowUsersListField) { 
        obj['AdditionalDataField'] = additionalDataField;
        obj['AutoRemindField'] = autoRemindField;
        obj['CustomMessageField'] = customMessageField;
        obj['DocField'] = docField;
        obj['DocNameField'] = docNameField;
        obj['DueDateField'] = dueDateField;
        obj['ExtensionField'] = extensionField;
        obj['FlattenDocumentField'] = flattenDocumentField;
        obj['KeepContentSecurityField'] = keepContentSecurityField;
        obj['KeepCustomPropertiesField'] = keepCustomPropertiesField;
        obj['KeepXMPMetadataField'] = keepXMPMetadataField;
        obj['PortfolioInformationField'] = portfolioInformationField;
        obj['PriorityField'] = priorityField;
        obj['SLAField'] = sLAField;
        obj['SendFirstEmailField'] = sendFirstEmailField;
        obj['SendWorkflowEmailsField'] = sendWorkflowEmailsField;
        obj['TokenField'] = tokenField;
        obj['WorkflowUsersListField'] = workflowUsersListField;
    }

    /**
     * Constructs a <code>FullWorkflowRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FullWorkflowRequest} obj Optional instance to populate.
     * @return {module:model/FullWorkflowRequest} The populated <code>FullWorkflowRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FullWorkflowRequest();

            if (data.hasOwnProperty('AdditionalDataField')) {
                obj['AdditionalDataField'] = ApiClient.convertToType(data['AdditionalDataField'], 'String');
            }
            if (data.hasOwnProperty('AutoRemindField')) {
                obj['AutoRemindField'] = AutoRemind.constructFromObject(data['AutoRemindField']);
            }
            if (data.hasOwnProperty('CustomMessageField')) {
                obj['CustomMessageField'] = ApiClient.convertToType(data['CustomMessageField'], 'String');
            }
            if (data.hasOwnProperty('DocField')) {
                obj['DocField'] = ApiClient.convertToType(data['DocField'], 'String');
            }
            if (data.hasOwnProperty('DocNameField')) {
                obj['DocNameField'] = ApiClient.convertToType(data['DocNameField'], 'String');
            }
            if (data.hasOwnProperty('DueDateField')) {
                obj['DueDateField'] = ApiClient.convertToType(data['DueDateField'], 'String');
            }
            if (data.hasOwnProperty('ExtensionField')) {
                obj['ExtensionField'] = DocExtension.constructFromObject(data['ExtensionField']);
            }
            if (data.hasOwnProperty('FlattenDocumentField')) {
                obj['FlattenDocumentField'] = ApiClient.convertToType(data['FlattenDocumentField'], 'Boolean');
            }
            if (data.hasOwnProperty('KeepContentSecurityField')) {
                obj['KeepContentSecurityField'] = ApiClient.convertToType(data['KeepContentSecurityField'], 'Boolean');
            }
            if (data.hasOwnProperty('KeepCustomPropertiesField')) {
                obj['KeepCustomPropertiesField'] = ApiClient.convertToType(data['KeepCustomPropertiesField'], 'Boolean');
            }
            if (data.hasOwnProperty('KeepXMPMetadataField')) {
                obj['KeepXMPMetadataField'] = ApiClient.convertToType(data['KeepXMPMetadataField'], 'Boolean');
            }
            if (data.hasOwnProperty('PortfolioInformationField')) {
                obj['PortfolioInformationField'] = FullWorkflowRequestPortfolioInformationField.constructFromObject(data['PortfolioInformationField']);
            }
            if (data.hasOwnProperty('PriorityField')) {
                obj['PriorityField'] = ApiClient.convertToType(data['PriorityField'], 'Number');
            }
            if (data.hasOwnProperty('SLAField')) {
                obj['SLAField'] = ApiClient.convertToType(data['SLAField'], 'Number');
            }
            if (data.hasOwnProperty('SendFirstEmailField')) {
                obj['SendFirstEmailField'] = ApiClient.convertToType(data['SendFirstEmailField'], 'Boolean');
            }
            if (data.hasOwnProperty('SendWorkflowEmailsField')) {
                obj['SendWorkflowEmailsField'] = ApiClient.convertToType(data['SendWorkflowEmailsField'], 'Boolean');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
            if (data.hasOwnProperty('WorkflowUsersListField')) {
                obj['WorkflowUsersListField'] = ApiClient.convertToType(data['WorkflowUsersListField'], [FullWorkflowRequestWorkflowUsersListField]);
            }
        }
        return obj;
    }


}

/**
 * Additional data.
 * @member {String} AdditionalDataField
 */
FullWorkflowRequest.prototype['AdditionalDataField'] = undefined;

/**
 * @member {module:model/AutoRemind} AutoRemindField
 */
FullWorkflowRequest.prototype['AutoRemindField'] = undefined;

/**
 * Custom message.
 * @member {String} CustomMessageField
 */
FullWorkflowRequest.prototype['CustomMessageField'] = undefined;

/**
 * Document field.
 * @member {String} DocField
 */
FullWorkflowRequest.prototype['DocField'] = undefined;

/**
 * Document name.
 * @member {String} DocNameField
 */
FullWorkflowRequest.prototype['DocNameField'] = undefined;

/**
 * Document due date.
 * @member {String} DueDateField
 */
FullWorkflowRequest.prototype['DueDateField'] = undefined;

/**
 * @member {module:model/DocExtension} ExtensionField
 */
FullWorkflowRequest.prototype['ExtensionField'] = undefined;

/**
 * Flatten document.
 * @member {Boolean} FlattenDocumentField
 */
FullWorkflowRequest.prototype['FlattenDocumentField'] = undefined;

/**
 * Keep content security.
 * @member {Boolean} KeepContentSecurityField
 */
FullWorkflowRequest.prototype['KeepContentSecurityField'] = undefined;

/**
 * Keep custom properties.
 * @member {Boolean} KeepCustomPropertiesField
 */
FullWorkflowRequest.prototype['KeepCustomPropertiesField'] = undefined;

/**
 * Keep XMP meta data.
 * @member {Boolean} KeepXMPMetadataField
 */
FullWorkflowRequest.prototype['KeepXMPMetadataField'] = undefined;

/**
 * @member {module:model/FullWorkflowRequestPortfolioInformationField} PortfolioInformationField
 */
FullWorkflowRequest.prototype['PortfolioInformationField'] = undefined;

/**
 * Document priority.
 * @member {Number} PriorityField
 */
FullWorkflowRequest.prototype['PriorityField'] = undefined;

/**
 * SLA
 * @member {Number} SLAField
 */
FullWorkflowRequest.prototype['SLAField'] = undefined;

/**
 * Confirm first user email notification will or will not be sent.
 * @member {Boolean} SendFirstEmailField
 */
FullWorkflowRequest.prototype['SendFirstEmailField'] = undefined;

/**
 * Confirm that workflow emails will or will not be sent.
 * @member {Boolean} SendWorkflowEmailsField
 */
FullWorkflowRequest.prototype['SendWorkflowEmailsField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
FullWorkflowRequest.prototype['TokenField'] = undefined;

/**
 * List of users in the workflow.
 * @member {Array.<module:model/FullWorkflowRequestWorkflowUsersListField>} WorkflowUsersListField
 */
FullWorkflowRequest.prototype['WorkflowUsersListField'] = undefined;






export default FullWorkflowRequest;

