/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FullWorkflowRequestWorkflowUserFieldsField model module.
 * @module model/FullWorkflowRequestWorkflowUserFieldsField
 * @version 1.0.1
 */
class FullWorkflowRequestWorkflowUserFieldsField {
    /**
     * Constructs a new <code>FullWorkflowRequestWorkflowUserFieldsField</code>.
     * @alias module:model/FullWorkflowRequestWorkflowUserFieldsField
     * @param fieldTypeField {Number} Field type.
     * @param fontFamilyField {String} The font family of the fields text.
     * @param fontSizeField {Number} The font size of the fields text.
     * @param groupUserNumberField {Number} The users in the group's user number.
     * @param heightField {String} Field height.
     * @param isInvisibleField {Boolean} Is the field visible.
     * @param pageNumberField {Number} Field page number.
     * @param tagNameField {String} Field tag name.
     * @param valueField {String} Field value.
     * @param widthField {String} Field width.
     * @param xCoordinateField {String} The fields x-coordinates.
     * @param xOffsetField {Number} The fields x-coordinates offset.
     * @param yCoordinateField {String} The fields y-coordinates.
     * @param yOffsetField {Number} The fields y-coordinates offset.
     */
    constructor(fieldTypeField, fontFamilyField, fontSizeField, groupUserNumberField, heightField, isInvisibleField, pageNumberField, tagNameField, valueField, widthField, xCoordinateField, xOffsetField, yCoordinateField, yOffsetField) { 
        
        FullWorkflowRequestWorkflowUserFieldsField.initialize(this, fieldTypeField, fontFamilyField, fontSizeField, groupUserNumberField, heightField, isInvisibleField, pageNumberField, tagNameField, valueField, widthField, xCoordinateField, xOffsetField, yCoordinateField, yOffsetField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fieldTypeField, fontFamilyField, fontSizeField, groupUserNumberField, heightField, isInvisibleField, pageNumberField, tagNameField, valueField, widthField, xCoordinateField, xOffsetField, yCoordinateField, yOffsetField) { 
        obj['FieldTypeField'] = fieldTypeField;
        obj['FontFamilyField'] = fontFamilyField;
        obj['FontSizeField'] = fontSizeField;
        obj['GroupUserNumberField'] = groupUserNumberField;
        obj['HeightField'] = heightField;
        obj['IsInvisibleField'] = isInvisibleField;
        obj['PageNumberField'] = pageNumberField;
        obj['TagNameField'] = tagNameField;
        obj['ValueField'] = valueField;
        obj['WidthField'] = widthField;
        obj['XCoordinateField'] = xCoordinateField;
        obj['XOffsetField'] = xOffsetField;
        obj['YCoordinateField'] = yCoordinateField;
        obj['YOffsetField'] = yOffsetField;
    }

    /**
     * Constructs a <code>FullWorkflowRequestWorkflowUserFieldsField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FullWorkflowRequestWorkflowUserFieldsField} obj Optional instance to populate.
     * @return {module:model/FullWorkflowRequestWorkflowUserFieldsField} The populated <code>FullWorkflowRequestWorkflowUserFieldsField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FullWorkflowRequestWorkflowUserFieldsField();

            if (data.hasOwnProperty('FieldTypeField')) {
                obj['FieldTypeField'] = ApiClient.convertToType(data['FieldTypeField'], 'Number');
            }
            if (data.hasOwnProperty('FontFamilyField')) {
                obj['FontFamilyField'] = ApiClient.convertToType(data['FontFamilyField'], 'String');
            }
            if (data.hasOwnProperty('FontSizeField')) {
                obj['FontSizeField'] = ApiClient.convertToType(data['FontSizeField'], 'Number');
            }
            if (data.hasOwnProperty('GroupUserNumberField')) {
                obj['GroupUserNumberField'] = ApiClient.convertToType(data['GroupUserNumberField'], 'Number');
            }
            if (data.hasOwnProperty('HeightField')) {
                obj['HeightField'] = ApiClient.convertToType(data['HeightField'], 'String');
            }
            if (data.hasOwnProperty('IsInvisibleField')) {
                obj['IsInvisibleField'] = ApiClient.convertToType(data['IsInvisibleField'], 'Boolean');
            }
            if (data.hasOwnProperty('PageNumberField')) {
                obj['PageNumberField'] = ApiClient.convertToType(data['PageNumberField'], 'Number');
            }
            if (data.hasOwnProperty('TagNameField')) {
                obj['TagNameField'] = ApiClient.convertToType(data['TagNameField'], 'String');
            }
            if (data.hasOwnProperty('ValueField')) {
                obj['ValueField'] = ApiClient.convertToType(data['ValueField'], 'String');
            }
            if (data.hasOwnProperty('WidthField')) {
                obj['WidthField'] = ApiClient.convertToType(data['WidthField'], 'String');
            }
            if (data.hasOwnProperty('XCoordinateField')) {
                obj['XCoordinateField'] = ApiClient.convertToType(data['XCoordinateField'], 'String');
            }
            if (data.hasOwnProperty('XOffsetField')) {
                obj['XOffsetField'] = ApiClient.convertToType(data['XOffsetField'], 'Number');
            }
            if (data.hasOwnProperty('YCoordinateField')) {
                obj['YCoordinateField'] = ApiClient.convertToType(data['YCoordinateField'], 'String');
            }
            if (data.hasOwnProperty('YOffsetField')) {
                obj['YOffsetField'] = ApiClient.convertToType(data['YOffsetField'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Field type.
 * @member {Number} FieldTypeField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['FieldTypeField'] = undefined;

/**
 * The font family of the fields text.
 * @member {String} FontFamilyField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['FontFamilyField'] = undefined;

/**
 * The font size of the fields text.
 * @member {Number} FontSizeField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['FontSizeField'] = undefined;

/**
 * The users in the group's user number.
 * @member {Number} GroupUserNumberField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['GroupUserNumberField'] = undefined;

/**
 * Field height.
 * @member {String} HeightField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['HeightField'] = undefined;

/**
 * Is the field visible.
 * @member {Boolean} IsInvisibleField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['IsInvisibleField'] = undefined;

/**
 * Field page number.
 * @member {Number} PageNumberField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['PageNumberField'] = undefined;

/**
 * Field tag name.
 * @member {String} TagNameField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['TagNameField'] = undefined;

/**
 * Field value.
 * @member {String} ValueField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['ValueField'] = undefined;

/**
 * Field width.
 * @member {String} WidthField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['WidthField'] = undefined;

/**
 * The fields x-coordinates.
 * @member {String} XCoordinateField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['XCoordinateField'] = undefined;

/**
 * The fields x-coordinates offset.
 * @member {Number} XOffsetField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['XOffsetField'] = undefined;

/**
 * The fields y-coordinates.
 * @member {String} YCoordinateField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['YCoordinateField'] = undefined;

/**
 * The fields y-coordinates offset.
 * @member {Number} YOffsetField
 */
FullWorkflowRequestWorkflowUserFieldsField.prototype['YOffsetField'] = undefined;






export default FullWorkflowRequestWorkflowUserFieldsField;

