/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FullWorkflowResponse model module.
 * @module model/FullWorkflowResponse
 * @version 1.0.1
 */
class FullWorkflowResponse {
    /**
     * Constructs a new <code>FullWorkflowResponse</code>.
     * #### The response returned on FullWorkflow.
     * @alias module:model/FullWorkflowResponse
     * @param docField {String} 
     * @param docIDField {Number} 
     * @param portfolioIDField {Number} 
     * @param resultField {String} Displays the result of the call.
     * @param statusField {String} 
     */
    constructor(docField, docIDField, portfolioIDField, resultField, statusField) { 
        
        FullWorkflowResponse.initialize(this, docField, docIDField, portfolioIDField, resultField, statusField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docField, docIDField, portfolioIDField, resultField, statusField) { 
        obj['DocField'] = docField;
        obj['DocIDField'] = docIDField;
        obj['PortfolioIDField'] = portfolioIDField;
        obj['ResultField'] = resultField;
        obj['StatusField'] = statusField;
    }

    /**
     * Constructs a <code>FullWorkflowResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FullWorkflowResponse} obj Optional instance to populate.
     * @return {module:model/FullWorkflowResponse} The populated <code>FullWorkflowResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FullWorkflowResponse();

            if (data.hasOwnProperty('DocField')) {
                obj['DocField'] = ApiClient.convertToType(data['DocField'], 'String');
            }
            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'Number');
            }
            if (data.hasOwnProperty('PortfolioIDField')) {
                obj['PortfolioIDField'] = ApiClient.convertToType(data['PortfolioIDField'], 'Number');
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
            if (data.hasOwnProperty('StatusField')) {
                obj['StatusField'] = ApiClient.convertToType(data['StatusField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} DocField
 */
FullWorkflowResponse.prototype['DocField'] = undefined;

/**
 * @member {Number} DocIDField
 */
FullWorkflowResponse.prototype['DocIDField'] = undefined;

/**
 * @member {Number} PortfolioIDField
 */
FullWorkflowResponse.prototype['PortfolioIDField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
FullWorkflowResponse.prototype['ResultField'] = undefined;

/**
 * @member {String} StatusField
 */
FullWorkflowResponse.prototype['StatusField'] = undefined;






export default FullWorkflowResponse;

