/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FullWorkflowRequestGroupStepField from './FullWorkflowRequestGroupStepField';
import FullWorkflowRequestWorkflowUserFieldsField from './FullWorkflowRequestWorkflowUserFieldsField';

/**
 * The FullWorkflowRequestWorkflowUsersListField model module.
 * @module model/FullWorkflowRequestWorkflowUsersListField
 * @version 1.0.1
 */
class FullWorkflowRequestWorkflowUsersListField {
    /**
     * Constructs a new <code>FullWorkflowRequestWorkflowUsersListField</code>.
     * @alias module:model/FullWorkflowRequestWorkflowUsersListField
     * @param actionField {Number} Refers to the order of signatures from the users.
     * @param allowProxyField {Number} Allow proxy confirmation field.
     * @param autoSignField {Boolean} ### Enable auto sign.  `True = Signature will be applied automaticly False = User will need to login and Sign` 
     * @param emailAddressField {String} Workflow user's email addresses.
     * @param languageCodeField {String} #### Sets the display language for the user ##### ISO 2 Digit Code  `en = English es = Spanish fr = French` 
     * @param latitudeField {String} Location latitude.
     * @param longitudeField {String} Location longtitude.
     * @param mobileNumberField {String} Group user's mobile number.
     * @param signReasonField {String} Reason for signature.
     * @param signerPasswordField {String} Face to face user's password.
     * @param userFirstNameField {String} Face to face user's first name.
     * @param userFullNameField {String} Face to face user's full name.
     * @param userLastNameField {String} Face to face user's last name.
     */
    constructor(actionField, allowProxyField, autoSignField, emailAddressField, languageCodeField, latitudeField, longitudeField, mobileNumberField, signReasonField, signerPasswordField, userFirstNameField, userFullNameField, userLastNameField) { 
        
        FullWorkflowRequestWorkflowUsersListField.initialize(this, actionField, allowProxyField, autoSignField, emailAddressField, languageCodeField, latitudeField, longitudeField, mobileNumberField, signReasonField, signerPasswordField, userFirstNameField, userFullNameField, userLastNameField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, actionField, allowProxyField, autoSignField, emailAddressField, languageCodeField, latitudeField, longitudeField, mobileNumberField, signReasonField, signerPasswordField, userFirstNameField, userFullNameField, userLastNameField) { 
        obj['ActionField'] = actionField;
        obj['AllowProxyField'] = allowProxyField;
        obj['AutoSignField'] = autoSignField;
        obj['EmailAddressField'] = emailAddressField;
        obj['LanguageCodeField'] = languageCodeField;
        obj['LatitudeField'] = latitudeField;
        obj['LongitudeField'] = longitudeField;
        obj['MobileNumberField'] = mobileNumberField;
        obj['SignReasonField'] = signReasonField;
        obj['SignerPasswordField'] = signerPasswordField;
        obj['UserFirstNameField'] = userFirstNameField;
        obj['UserFullNameField'] = userFullNameField;
        obj['UserLastNameField'] = userLastNameField;
    }

    /**
     * Constructs a <code>FullWorkflowRequestWorkflowUsersListField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FullWorkflowRequestWorkflowUsersListField} obj Optional instance to populate.
     * @return {module:model/FullWorkflowRequestWorkflowUsersListField} The populated <code>FullWorkflowRequestWorkflowUsersListField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FullWorkflowRequestWorkflowUsersListField();

            if (data.hasOwnProperty('ActionField')) {
                obj['ActionField'] = ApiClient.convertToType(data['ActionField'], 'Number');
            }
            if (data.hasOwnProperty('AllowProxyField')) {
                obj['AllowProxyField'] = ApiClient.convertToType(data['AllowProxyField'], 'Number');
            }
            if (data.hasOwnProperty('AutoSignField')) {
                obj['AutoSignField'] = ApiClient.convertToType(data['AutoSignField'], 'Boolean');
            }
            if (data.hasOwnProperty('EmailAddressField')) {
                obj['EmailAddressField'] = ApiClient.convertToType(data['EmailAddressField'], 'String');
            }
            if (data.hasOwnProperty('GroupStepField')) {
                obj['GroupStepField'] = FullWorkflowRequestGroupStepField.constructFromObject(data['GroupStepField']);
            }
            if (data.hasOwnProperty('LanguageCodeField')) {
                obj['LanguageCodeField'] = ApiClient.convertToType(data['LanguageCodeField'], 'String');
            }
            if (data.hasOwnProperty('LatitudeField')) {
                obj['LatitudeField'] = ApiClient.convertToType(data['LatitudeField'], 'String');
            }
            if (data.hasOwnProperty('LongitudeField')) {
                obj['LongitudeField'] = ApiClient.convertToType(data['LongitudeField'], 'String');
            }
            if (data.hasOwnProperty('MobileNumberField')) {
                obj['MobileNumberField'] = ApiClient.convertToType(data['MobileNumberField'], 'String');
            }
            if (data.hasOwnProperty('PreloadedFaceToFaceSignersField')) {
                obj['PreloadedFaceToFaceSignersField'] = ApiClient.convertToType(data['PreloadedFaceToFaceSignersField'], [Object]);
            }
            if (data.hasOwnProperty('SignReasonField')) {
                obj['SignReasonField'] = ApiClient.convertToType(data['SignReasonField'], 'String');
            }
            if (data.hasOwnProperty('SignerPasswordField')) {
                obj['SignerPasswordField'] = ApiClient.convertToType(data['SignerPasswordField'], 'String');
            }
            if (data.hasOwnProperty('UserFirstNameField')) {
                obj['UserFirstNameField'] = ApiClient.convertToType(data['UserFirstNameField'], 'String');
            }
            if (data.hasOwnProperty('UserFullNameField')) {
                obj['UserFullNameField'] = ApiClient.convertToType(data['UserFullNameField'], 'String');
            }
            if (data.hasOwnProperty('UserLastNameField')) {
                obj['UserLastNameField'] = ApiClient.convertToType(data['UserLastNameField'], 'String');
            }
            if (data.hasOwnProperty('WorkflowUserFieldsField')) {
                obj['WorkflowUserFieldsField'] = ApiClient.convertToType(data['WorkflowUserFieldsField'], [FullWorkflowRequestWorkflowUserFieldsField]);
            }
        }
        return obj;
    }


}

/**
 * Refers to the order of signatures from the users.
 * @member {Number} ActionField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['ActionField'] = undefined;

/**
 * Allow proxy confirmation field.
 * @member {Number} AllowProxyField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['AllowProxyField'] = undefined;

/**
 * ### Enable auto sign.  `True = Signature will be applied automaticly False = User will need to login and Sign` 
 * @member {Boolean} AutoSignField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['AutoSignField'] = undefined;

/**
 * Workflow user's email addresses.
 * @member {String} EmailAddressField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['EmailAddressField'] = undefined;

/**
 * @member {module:model/FullWorkflowRequestGroupStepField} GroupStepField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['GroupStepField'] = undefined;

/**
 * #### Sets the display language for the user ##### ISO 2 Digit Code  `en = English es = Spanish fr = French` 
 * @member {String} LanguageCodeField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['LanguageCodeField'] = undefined;

/**
 * Location latitude.
 * @member {String} LatitudeField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['LatitudeField'] = undefined;

/**
 * Location longtitude.
 * @member {String} LongitudeField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['LongitudeField'] = undefined;

/**
 * Group user's mobile number.
 * @member {String} MobileNumberField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['MobileNumberField'] = undefined;

/**
 * Preloaded user's who will be using the face to face signature field.
 * @member {Array.<Object>} PreloadedFaceToFaceSignersField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['PreloadedFaceToFaceSignersField'] = undefined;

/**
 * Reason for signature.
 * @member {String} SignReasonField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['SignReasonField'] = undefined;

/**
 * Face to face user's password.
 * @member {String} SignerPasswordField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['SignerPasswordField'] = undefined;

/**
 * Face to face user's first name.
 * @member {String} UserFirstNameField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['UserFirstNameField'] = undefined;

/**
 * Face to face user's full name.
 * @member {String} UserFullNameField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['UserFullNameField'] = undefined;

/**
 * Face to face user's last name.
 * @member {String} UserLastNameField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['UserLastNameField'] = undefined;

/**
 * The list of the workflowed documents field.
 * @member {Array.<module:model/FullWorkflowRequestWorkflowUserFieldsField>} WorkflowUserFieldsField
 */
FullWorkflowRequestWorkflowUsersListField.prototype['WorkflowUserFieldsField'] = undefined;






export default FullWorkflowRequestWorkflowUsersListField;

