/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FullWorkflowRequestGroupStepFieldGroupMembersField model module.
 * @module model/FullWorkflowRequestGroupStepFieldGroupMembersField
 * @version 1.0.1
 */
class FullWorkflowRequestGroupStepFieldGroupMembersField {
    /**
     * Constructs a new <code>FullWorkflowRequestGroupStepFieldGroupMembersField</code>.
     * @alias module:model/FullWorkflowRequestGroupStepFieldGroupMembersField
     * @param languageCodeField {String} 
     * @param userEmailField {String} 
     * @param userFullNameField {String} 
     * @param userMobileNumberField {String} 
     */
    constructor(languageCodeField, userEmailField, userFullNameField, userMobileNumberField) { 
        
        FullWorkflowRequestGroupStepFieldGroupMembersField.initialize(this, languageCodeField, userEmailField, userFullNameField, userMobileNumberField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, languageCodeField, userEmailField, userFullNameField, userMobileNumberField) { 
        obj['LanguageCodeField'] = languageCodeField;
        obj['UserEmailField'] = userEmailField;
        obj['UserFullNameField'] = userFullNameField;
        obj['UserMobileNumberField'] = userMobileNumberField;
    }

    /**
     * Constructs a <code>FullWorkflowRequestGroupStepFieldGroupMembersField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FullWorkflowRequestGroupStepFieldGroupMembersField} obj Optional instance to populate.
     * @return {module:model/FullWorkflowRequestGroupStepFieldGroupMembersField} The populated <code>FullWorkflowRequestGroupStepFieldGroupMembersField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FullWorkflowRequestGroupStepFieldGroupMembersField();

            if (data.hasOwnProperty('LanguageCodeField')) {
                obj['LanguageCodeField'] = ApiClient.convertToType(data['LanguageCodeField'], 'String');
            }
            if (data.hasOwnProperty('UserEmailField')) {
                obj['UserEmailField'] = ApiClient.convertToType(data['UserEmailField'], 'String');
            }
            if (data.hasOwnProperty('UserFullNameField')) {
                obj['UserFullNameField'] = ApiClient.convertToType(data['UserFullNameField'], 'String');
            }
            if (data.hasOwnProperty('UserMobileNumberField')) {
                obj['UserMobileNumberField'] = ApiClient.convertToType(data['UserMobileNumberField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} LanguageCodeField
 */
FullWorkflowRequestGroupStepFieldGroupMembersField.prototype['LanguageCodeField'] = undefined;

/**
 * @member {String} UserEmailField
 */
FullWorkflowRequestGroupStepFieldGroupMembersField.prototype['UserEmailField'] = undefined;

/**
 * @member {String} UserFullNameField
 */
FullWorkflowRequestGroupStepFieldGroupMembersField.prototype['UserFullNameField'] = undefined;

/**
 * @member {String} UserMobileNumberField
 */
FullWorkflowRequestGroupStepFieldGroupMembersField.prototype['UserMobileNumberField'] = undefined;






export default FullWorkflowRequestGroupStepFieldGroupMembersField;

