/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FullWorkflowRequestGroupStepFieldGroupMembersField from './FullWorkflowRequestGroupStepFieldGroupMembersField';

/**
 * The FullWorkflowRequestGroupStepField model module.
 * @module model/FullWorkflowRequestGroupStepField
 * @version 1.0.1
 */
class FullWorkflowRequestGroupStepField {
    /**
     * Constructs a new <code>FullWorkflowRequestGroupStepField</code>.
     * Steps of the group signers in the workflow.
     * @alias module:model/FullWorkflowRequestGroupStepField
     * @param groupMembersField {Array.<module:model/FullWorkflowRequestGroupStepFieldGroupMembersField>} The list of users in a group in the workflow.
     * @param groupNameField {String} Group name.
     * @param requiredNumberOfSignaturesField {Number} Required number of signatures in the group.
     */
    constructor(groupMembersField, groupNameField, requiredNumberOfSignaturesField) { 
        
        FullWorkflowRequestGroupStepField.initialize(this, groupMembersField, groupNameField, requiredNumberOfSignaturesField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groupMembersField, groupNameField, requiredNumberOfSignaturesField) { 
        obj['GroupMembersField'] = groupMembersField;
        obj['GroupNameField'] = groupNameField;
        obj['RequiredNumberOfSignaturesField'] = requiredNumberOfSignaturesField;
    }

    /**
     * Constructs a <code>FullWorkflowRequestGroupStepField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FullWorkflowRequestGroupStepField} obj Optional instance to populate.
     * @return {module:model/FullWorkflowRequestGroupStepField} The populated <code>FullWorkflowRequestGroupStepField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FullWorkflowRequestGroupStepField();

            if (data.hasOwnProperty('GroupMembersField')) {
                obj['GroupMembersField'] = ApiClient.convertToType(data['GroupMembersField'], [FullWorkflowRequestGroupStepFieldGroupMembersField]);
            }
            if (data.hasOwnProperty('GroupNameField')) {
                obj['GroupNameField'] = ApiClient.convertToType(data['GroupNameField'], 'String');
            }
            if (data.hasOwnProperty('RequiredNumberOfSignaturesField')) {
                obj['RequiredNumberOfSignaturesField'] = ApiClient.convertToType(data['RequiredNumberOfSignaturesField'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The list of users in a group in the workflow.
 * @member {Array.<module:model/FullWorkflowRequestGroupStepFieldGroupMembersField>} GroupMembersField
 */
FullWorkflowRequestGroupStepField.prototype['GroupMembersField'] = undefined;

/**
 * Group name.
 * @member {String} GroupNameField
 */
FullWorkflowRequestGroupStepField.prototype['GroupNameField'] = undefined;

/**
 * Required number of signatures in the group.
 * @member {Number} RequiredNumberOfSignaturesField
 */
FullWorkflowRequestGroupStepField.prototype['RequiredNumberOfSignaturesField'] = undefined;






export default FullWorkflowRequestGroupStepField;

