/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAuditDocumentResponse model module.
 * @module model/GetAuditDocumentResponse
 * @version 1.0.1
 */
class GetAuditDocumentResponse {
    /**
     * Constructs a new <code>GetAuditDocumentResponse</code>.
     * #### The response returned when requesting and audit document.
     * @alias module:model/GetAuditDocumentResponse
     * @param auditDocumentField {String} 
     * @param resultField {String} Displays the result of the call.
     */
    constructor(auditDocumentField, resultField) { 
        
        GetAuditDocumentResponse.initialize(this, auditDocumentField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, auditDocumentField, resultField) { 
        obj['AuditDocumentField'] = auditDocumentField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>GetAuditDocumentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAuditDocumentResponse} obj Optional instance to populate.
     * @return {module:model/GetAuditDocumentResponse} The populated <code>GetAuditDocumentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAuditDocumentResponse();

            if (data.hasOwnProperty('AuditDocumentField')) {
                obj['AuditDocumentField'] = ApiClient.convertToType(data['AuditDocumentField'], 'String');
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} AuditDocumentField
 */
GetAuditDocumentResponse.prototype['AuditDocumentField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
GetAuditDocumentResponse.prototype['ResultField'] = undefined;






export default GetAuditDocumentResponse;

