/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetDocLinkResponse model module.
 * @module model/GetDocLinkResponse
 * @version 1.0.1
 */
class GetDocLinkResponse {
    /**
     * Constructs a new <code>GetDocLinkResponse</code>.
     * #### This is the response returned when a document url is requested.
     * @alias module:model/GetDocLinkResponse
     * @param result {String} Displays the result of the call.
     * @param url {String} URL
     */
    constructor(result, url) { 
        
        GetDocLinkResponse.initialize(this, result, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, result, url) { 
        obj['Result'] = result;
        obj['Url'] = url;
    }

    /**
     * Constructs a <code>GetDocLinkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDocLinkResponse} obj Optional instance to populate.
     * @return {module:model/GetDocLinkResponse} The populated <code>GetDocLinkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDocLinkResponse();

            if (data.hasOwnProperty('Result')) {
                obj['Result'] = ApiClient.convertToType(data['Result'], 'String');
            }
            if (data.hasOwnProperty('Url')) {
                obj['Url'] = ApiClient.convertToType(data['Url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Displays the result of the call.
 * @member {String} Result
 */
GetDocLinkResponse.prototype['Result'] = undefined;

/**
 * URL
 * @member {String} Url
 */
GetDocLinkResponse.prototype['Url'] = undefined;






export default GetDocLinkResponse;

