/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The GetDocumentTagFieldBoxPositionRequest model module.
 * @module model/GetDocumentTagFieldBoxPositionRequest
 * @version 1.0.1
 */
class GetDocumentTagFieldBoxPositionRequest {
    /**
     * Constructs a new <code>GetDocumentTagFieldBoxPositionRequest</code>.
     * #### The request sent to get the document tag field box position.
     * @alias module:model/GetDocumentTagFieldBoxPositionRequest
     * @param docIDField {Number} 
     * @param tagNameField {String} 
     * @param tokenField {module:model/TokenField} 
     */
    constructor(docIDField, tagNameField, tokenField) { 
        
        GetDocumentTagFieldBoxPositionRequest.initialize(this, docIDField, tagNameField, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, tagNameField, tokenField) { 
        obj['DocIDField'] = docIDField;
        obj['TagNameField'] = tagNameField;
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>GetDocumentTagFieldBoxPositionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDocumentTagFieldBoxPositionRequest} obj Optional instance to populate.
     * @return {module:model/GetDocumentTagFieldBoxPositionRequest} The populated <code>GetDocumentTagFieldBoxPositionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDocumentTagFieldBoxPositionRequest();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'Number');
            }
            if (data.hasOwnProperty('TagNameField')) {
                obj['TagNameField'] = ApiClient.convertToType(data['TagNameField'], 'String');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} DocIDField
 */
GetDocumentTagFieldBoxPositionRequest.prototype['DocIDField'] = undefined;

/**
 * @member {String} TagNameField
 */
GetDocumentTagFieldBoxPositionRequest.prototype['TagNameField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
GetDocumentTagFieldBoxPositionRequest.prototype['TokenField'] = undefined;






export default GetDocumentTagFieldBoxPositionRequest;

