/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetDocStatusResponse model module.
 * @module model/GetDocStatusResponse
 * @version 1.0.1
 */
class GetDocStatusResponse {
    /**
     * Constructs a new <code>GetDocStatusResponse</code>.
     * #### This is the response returned when a document status has been requested.
     * @alias module:model/GetDocStatusResponse
     * @param docStatusField {String} Status of the document.
     * @param resultField {String} Displays the result of the call.
     */
    constructor(docStatusField, resultField) { 
        
        GetDocStatusResponse.initialize(this, docStatusField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docStatusField, resultField) { 
        obj['DocStatusField'] = docStatusField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>GetDocStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDocStatusResponse} obj Optional instance to populate.
     * @return {module:model/GetDocStatusResponse} The populated <code>GetDocStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDocStatusResponse();

            if (data.hasOwnProperty('DocStatusField')) {
                obj['DocStatusField'] = ApiClient.convertToType(data['DocStatusField'], 'String');
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Status of the document.
 * @member {String} DocStatusField
 */
GetDocStatusResponse.prototype['DocStatusField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
GetDocStatusResponse.prototype['ResultField'] = undefined;






export default GetDocStatusResponse;

