/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField from './GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField';

/**
 * The GetDocumentTagFieldBoxPositionResponse model module.
 * @module model/GetDocumentTagFieldBoxPositionResponse
 * @version 1.0.1
 */
class GetDocumentTagFieldBoxPositionResponse {
    /**
     * Constructs a new <code>GetDocumentTagFieldBoxPositionResponse</code>.
     * #### The response returned after requesting the document tag field ox position.
     * @alias module:model/GetDocumentTagFieldBoxPositionResponse
     * @param documentTagFieldsBoxPositionField {module:model/GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField} 
     * @param resultField {String} Displays the result of the call.
     */
    constructor(documentTagFieldsBoxPositionField, resultField) { 
        
        GetDocumentTagFieldBoxPositionResponse.initialize(this, documentTagFieldsBoxPositionField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentTagFieldsBoxPositionField, resultField) { 
        obj['DocumentTagFieldsBoxPositionField'] = documentTagFieldsBoxPositionField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>GetDocumentTagFieldBoxPositionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDocumentTagFieldBoxPositionResponse} obj Optional instance to populate.
     * @return {module:model/GetDocumentTagFieldBoxPositionResponse} The populated <code>GetDocumentTagFieldBoxPositionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDocumentTagFieldBoxPositionResponse();

            if (data.hasOwnProperty('DocumentTagFieldsBoxPositionField')) {
                obj['DocumentTagFieldsBoxPositionField'] = GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField.constructFromObject(data['DocumentTagFieldsBoxPositionField']);
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField} DocumentTagFieldsBoxPositionField
 */
GetDocumentTagFieldBoxPositionResponse.prototype['DocumentTagFieldsBoxPositionField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
GetDocumentTagFieldBoxPositionResponse.prototype['ResultField'] = undefined;






export default GetDocumentTagFieldBoxPositionResponse;

