/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetDocumentAuditResponseActivityField model module.
 * @module model/GetDocumentAuditResponseActivityField
 * @version 1.0.1
 */
class GetDocumentAuditResponseActivityField {
    /**
     * Constructs a new <code>GetDocumentAuditResponseActivityField</code>.
     * @alias module:model/GetDocumentAuditResponseActivityField
     * @param actionOrderField {String} 
     * @param additionalField {String} 
     * @param docIDField {String} 
     * @param emailField {String} The user's email.
     * @param eventDateField {String} 
     * @param eventField {String} 
     * @param eventStatusField {String} 
     * @param locationField {String} 
     * @param orderDateField {String} 
     * @param pageField {String} 
     * @param userFullNameField {String} User's full name.
     */
    constructor(actionOrderField, additionalField, docIDField, emailField, eventDateField, eventField, eventStatusField, locationField, orderDateField, pageField, userFullNameField) { 
        
        GetDocumentAuditResponseActivityField.initialize(this, actionOrderField, additionalField, docIDField, emailField, eventDateField, eventField, eventStatusField, locationField, orderDateField, pageField, userFullNameField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, actionOrderField, additionalField, docIDField, emailField, eventDateField, eventField, eventStatusField, locationField, orderDateField, pageField, userFullNameField) { 
        obj['ActionOrderField'] = actionOrderField;
        obj['AdditionalField'] = additionalField;
        obj['DocIDField'] = docIDField;
        obj['EmailField'] = emailField;
        obj['EventDateField'] = eventDateField;
        obj['EventField'] = eventField;
        obj['EventStatusField'] = eventStatusField;
        obj['LocationField'] = locationField;
        obj['OrderDateField'] = orderDateField;
        obj['PageField'] = pageField;
        obj['UserFullNameField'] = userFullNameField;
    }

    /**
     * Constructs a <code>GetDocumentAuditResponseActivityField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDocumentAuditResponseActivityField} obj Optional instance to populate.
     * @return {module:model/GetDocumentAuditResponseActivityField} The populated <code>GetDocumentAuditResponseActivityField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDocumentAuditResponseActivityField();

            if (data.hasOwnProperty('ActionOrderField')) {
                obj['ActionOrderField'] = ApiClient.convertToType(data['ActionOrderField'], 'String');
            }
            if (data.hasOwnProperty('AdditionalField')) {
                obj['AdditionalField'] = ApiClient.convertToType(data['AdditionalField'], 'String');
            }
            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'String');
            }
            if (data.hasOwnProperty('EmailField')) {
                obj['EmailField'] = ApiClient.convertToType(data['EmailField'], 'String');
            }
            if (data.hasOwnProperty('EventDateField')) {
                obj['EventDateField'] = ApiClient.convertToType(data['EventDateField'], 'String');
            }
            if (data.hasOwnProperty('EventField')) {
                obj['EventField'] = ApiClient.convertToType(data['EventField'], 'String');
            }
            if (data.hasOwnProperty('EventStatusField')) {
                obj['EventStatusField'] = ApiClient.convertToType(data['EventStatusField'], 'String');
            }
            if (data.hasOwnProperty('LocationField')) {
                obj['LocationField'] = ApiClient.convertToType(data['LocationField'], 'String');
            }
            if (data.hasOwnProperty('OrderDateField')) {
                obj['OrderDateField'] = ApiClient.convertToType(data['OrderDateField'], 'String');
            }
            if (data.hasOwnProperty('PageField')) {
                obj['PageField'] = ApiClient.convertToType(data['PageField'], 'String');
            }
            if (data.hasOwnProperty('UserFullNameField')) {
                obj['UserFullNameField'] = ApiClient.convertToType(data['UserFullNameField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} ActionOrderField
 */
GetDocumentAuditResponseActivityField.prototype['ActionOrderField'] = undefined;

/**
 * @member {String} AdditionalField
 */
GetDocumentAuditResponseActivityField.prototype['AdditionalField'] = undefined;

/**
 * @member {String} DocIDField
 */
GetDocumentAuditResponseActivityField.prototype['DocIDField'] = undefined;

/**
 * The user's email.
 * @member {String} EmailField
 */
GetDocumentAuditResponseActivityField.prototype['EmailField'] = undefined;

/**
 * @member {String} EventDateField
 */
GetDocumentAuditResponseActivityField.prototype['EventDateField'] = undefined;

/**
 * @member {String} EventField
 */
GetDocumentAuditResponseActivityField.prototype['EventField'] = undefined;

/**
 * @member {String} EventStatusField
 */
GetDocumentAuditResponseActivityField.prototype['EventStatusField'] = undefined;

/**
 * @member {String} LocationField
 */
GetDocumentAuditResponseActivityField.prototype['LocationField'] = undefined;

/**
 * @member {String} OrderDateField
 */
GetDocumentAuditResponseActivityField.prototype['OrderDateField'] = undefined;

/**
 * @member {String} PageField
 */
GetDocumentAuditResponseActivityField.prototype['PageField'] = undefined;

/**
 * User's full name.
 * @member {String} UserFullNameField
 */
GetDocumentAuditResponseActivityField.prototype['UserFullNameField'] = undefined;






export default GetDocumentAuditResponseActivityField;

