/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetDocumentAuditResponseActivityField from './GetDocumentAuditResponseActivityField';

/**
 * The GetDocumentAuditResponse model module.
 * @module model/GetDocumentAuditResponse
 * @version 1.0.1
 */
class GetDocumentAuditResponse {
    /**
     * Constructs a new <code>GetDocumentAuditResponse</code>.
     * #### The response returned after requesting the audit information from a document.
     * @alias module:model/GetDocumentAuditResponse
     * @param activityField {Array.<module:model/GetDocumentAuditResponseActivityField>} 
     * @param resultField {String} Displays the result of the call.
     */
    constructor(activityField, resultField) { 
        
        GetDocumentAuditResponse.initialize(this, activityField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, activityField, resultField) { 
        obj['ActivityField'] = activityField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>GetDocumentAuditResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDocumentAuditResponse} obj Optional instance to populate.
     * @return {module:model/GetDocumentAuditResponse} The populated <code>GetDocumentAuditResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDocumentAuditResponse();

            if (data.hasOwnProperty('ActivityField')) {
                obj['ActivityField'] = ApiClient.convertToType(data['ActivityField'], [GetDocumentAuditResponseActivityField]);
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/GetDocumentAuditResponseActivityField>} ActivityField
 */
GetDocumentAuditResponse.prototype['ActivityField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
GetDocumentAuditResponse.prototype['ResultField'] = undefined;






export default GetDocumentAuditResponse;

