/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField from './GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField';

/**
 * The GetDocumentTagFieldPositionResponse model module.
 * @module model/GetDocumentTagFieldPositionResponse
 * @version 1.0.1
 */
class GetDocumentTagFieldPositionResponse {
    /**
     * Constructs a new <code>GetDocumentTagFieldPositionResponse</code>.
     * #### The response returned when requesting the document tag field position.
     * @alias module:model/GetDocumentTagFieldPositionResponse
     * @param documentTagFieldsPositionField {Array.<module:model/GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField>} 
     * @param resultField {String} Displays the result of the call.
     */
    constructor(documentTagFieldsPositionField, resultField) { 
        
        GetDocumentTagFieldPositionResponse.initialize(this, documentTagFieldsPositionField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentTagFieldsPositionField, resultField) { 
        obj['DocumentTagFieldsPositionField'] = documentTagFieldsPositionField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>GetDocumentTagFieldPositionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDocumentTagFieldPositionResponse} obj Optional instance to populate.
     * @return {module:model/GetDocumentTagFieldPositionResponse} The populated <code>GetDocumentTagFieldPositionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDocumentTagFieldPositionResponse();

            if (data.hasOwnProperty('DocumentTagFieldsPositionField')) {
                obj['DocumentTagFieldsPositionField'] = ApiClient.convertToType(data['DocumentTagFieldsPositionField'], [GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField]);
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField>} DocumentTagFieldsPositionField
 */
GetDocumentTagFieldPositionResponse.prototype['DocumentTagFieldsPositionField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
GetDocumentTagFieldPositionResponse.prototype['ResultField'] = undefined;






export default GetDocumentTagFieldPositionResponse;

