/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetPrepperTemplateListResponseTemplateInformationValuesField from './GetPrepperTemplateListResponseTemplateInformationValuesField';

/**
 * The GetPrepperTemplateListResponse model module.
 * @module model/GetPrepperTemplateListResponse
 * @version 1.0.1
 */
class GetPrepperTemplateListResponse {
    /**
     * Constructs a new <code>GetPrepperTemplateListResponse</code>.
     * #### The response returned when the document template list gets requested.
     * @alias module:model/GetPrepperTemplateListResponse
     * @param resultField {String} Displays the result of the call.
     * @param templateInformationValuesField {Array.<module:model/GetPrepperTemplateListResponseTemplateInformationValuesField>} 
     */
    constructor(resultField, templateInformationValuesField) { 
        
        GetPrepperTemplateListResponse.initialize(this, resultField, templateInformationValuesField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resultField, templateInformationValuesField) { 
        obj['ResultField'] = resultField;
        obj['TemplateInformationValuesField'] = templateInformationValuesField;
    }

    /**
     * Constructs a <code>GetPrepperTemplateListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPrepperTemplateListResponse} obj Optional instance to populate.
     * @return {module:model/GetPrepperTemplateListResponse} The populated <code>GetPrepperTemplateListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPrepperTemplateListResponse();

            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
            if (data.hasOwnProperty('TemplateInformationValuesField')) {
                obj['TemplateInformationValuesField'] = ApiClient.convertToType(data['TemplateInformationValuesField'], [GetPrepperTemplateListResponseTemplateInformationValuesField]);
            }
        }
        return obj;
    }


}

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
GetPrepperTemplateListResponse.prototype['ResultField'] = undefined;

/**
 * @member {Array.<module:model/GetPrepperTemplateListResponseTemplateInformationValuesField>} TemplateInformationValuesField
 */
GetPrepperTemplateListResponse.prototype['TemplateInformationValuesField'] = undefined;






export default GetPrepperTemplateListResponse;

