/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The GetPrepperTemplateRequest model module.
 * @module model/GetPrepperTemplateRequest
 * @version 1.0.1
 */
class GetPrepperTemplateRequest {
    /**
     * Constructs a new <code>GetPrepperTemplateRequest</code>.
     * #### The request used to get templates.
     * @alias module:model/GetPrepperTemplateRequest
     * @param docIDField {Number} 
     * @param prepperTemplateIDField {Number} 
     * @param tokenField {module:model/TokenField} 
     */
    constructor(docIDField, prepperTemplateIDField, tokenField) { 
        
        GetPrepperTemplateRequest.initialize(this, docIDField, prepperTemplateIDField, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, prepperTemplateIDField, tokenField) { 
        obj['DocIDField'] = docIDField;
        obj['PrepperTemplateIDField'] = prepperTemplateIDField;
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>GetPrepperTemplateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPrepperTemplateRequest} obj Optional instance to populate.
     * @return {module:model/GetPrepperTemplateRequest} The populated <code>GetPrepperTemplateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPrepperTemplateRequest();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'Number');
            }
            if (data.hasOwnProperty('PrepperTemplateIDField')) {
                obj['PrepperTemplateIDField'] = ApiClient.convertToType(data['PrepperTemplateIDField'], 'Number');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} DocIDField
 */
GetPrepperTemplateRequest.prototype['DocIDField'] = undefined;

/**
 * @member {Number} PrepperTemplateIDField
 */
GetPrepperTemplateRequest.prototype['PrepperTemplateIDField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
GetPrepperTemplateRequest.prototype['TokenField'] = undefined;






export default GetPrepperTemplateRequest;

