/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InitiateFlowNoEmailResponse model module.
 * @module model/InitiateFlowNoEmailResponse
 * @version 1.0.1
 */
class InitiateFlowNoEmailResponse {
    /**
     * Constructs a new <code>InitiateFlowNoEmailResponse</code>.
     * #### The response returned when a workflow is requested without any email.
     * @alias module:model/InitiateFlowNoEmailResponse
     * @param docIDField {Number} The document ID.
     * @param resultField {String} Displays the result of the call.
     */
    constructor(docIDField, resultField) { 
        
        InitiateFlowNoEmailResponse.initialize(this, docIDField, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, resultField) { 
        obj['DocIDField'] = docIDField;
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>InitiateFlowNoEmailResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InitiateFlowNoEmailResponse} obj Optional instance to populate.
     * @return {module:model/InitiateFlowNoEmailResponse} The populated <code>InitiateFlowNoEmailResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InitiateFlowNoEmailResponse();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'Number');
            }
            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The document ID.
 * @member {Number} DocIDField
 */
InitiateFlowNoEmailResponse.prototype['DocIDField'] = undefined;

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
InitiateFlowNoEmailResponse.prototype['ResultField'] = undefined;






export default InitiateFlowNoEmailResponse;

