/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The LinkToPortfolioRequest model module.
 * @module model/LinkToPortfolioRequest
 * @version 1.0.1
 */
class LinkToPortfolioRequest {
    /**
     * Constructs a new <code>LinkToPortfolioRequest</code>.
     * #### This request is used to get the url link to a portfolio.
     * @alias module:model/LinkToPortfolioRequest
     * @param docIDField {String} The document ID.
     * @param documentNameField {String} Document name.
     * @param portfolioIDField {String} The portfolio ID.
     * @param tokenField {module:model/TokenField} 
     */
    constructor(docIDField, documentNameField, portfolioIDField, tokenField) { 
        
        LinkToPortfolioRequest.initialize(this, docIDField, documentNameField, portfolioIDField, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, documentNameField, portfolioIDField, tokenField) { 
        obj['DocIDField'] = docIDField;
        obj['DocumentNameField'] = documentNameField;
        obj['PortfolioIDField'] = portfolioIDField;
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>LinkToPortfolioRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LinkToPortfolioRequest} obj Optional instance to populate.
     * @return {module:model/LinkToPortfolioRequest} The populated <code>LinkToPortfolioRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LinkToPortfolioRequest();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'String');
            }
            if (data.hasOwnProperty('DocumentNameField')) {
                obj['DocumentNameField'] = ApiClient.convertToType(data['DocumentNameField'], 'String');
            }
            if (data.hasOwnProperty('PortfolioIDField')) {
                obj['PortfolioIDField'] = ApiClient.convertToType(data['PortfolioIDField'], 'String');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
        }
        return obj;
    }


}

/**
 * The document ID.
 * @member {String} DocIDField
 */
LinkToPortfolioRequest.prototype['DocIDField'] = undefined;

/**
 * Document name.
 * @member {String} DocumentNameField
 */
LinkToPortfolioRequest.prototype['DocumentNameField'] = undefined;

/**
 * The portfolio ID.
 * @member {String} PortfolioIDField
 */
LinkToPortfolioRequest.prototype['PortfolioIDField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
LinkToPortfolioRequest.prototype['TokenField'] = undefined;






export default LinkToPortfolioRequest;

