/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The LogoutResponse model module.
 * @module model/LogoutResponse
 * @version 1.0.1
 */
class LogoutResponse {
    /**
     * Constructs a new <code>LogoutResponse</code>.
     * #### The response returned when a user logs out.
     * @alias module:model/LogoutResponse
     * @param resultField {String} Displays the result of the call.
     * @param tokenField {module:model/TokenField} 
     */
    constructor(resultField, tokenField) { 
        
        LogoutResponse.initialize(this, resultField, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resultField, tokenField) { 
        obj['ResultField'] = resultField;
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>LogoutResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LogoutResponse} obj Optional instance to populate.
     * @return {module:model/LogoutResponse} The populated <code>LogoutResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LogoutResponse();

            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
        }
        return obj;
    }


}

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
LogoutResponse.prototype['ResultField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
LogoutResponse.prototype['TokenField'] = undefined;






export default LogoutResponse;

