/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MultipleSignersSigningCeremonyRequestSignerListField from './MultipleSignersSigningCeremonyRequestSignerListField';

/**
 * The MultipleSignersSigningCeremonyRequest model module.
 * @module model/MultipleSignersSigningCeremonyRequest
 * @version 1.0.1
 */
class MultipleSignersSigningCeremonyRequest {
    /**
     * Constructs a new <code>MultipleSignersSigningCeremonyRequest</code>.
     * #### This is the request sent when there are multiple signers on a document.
     * @alias module:model/MultipleSignersSigningCeremonyRequest
     * @param docField {String} 
     * @param docNameField {String} 
     * @param loginPasswordField {String} User's password.
     * @param loginUserNameField {String} User's username.
     * @param signerListField {Array.<module:model/MultipleSignersSigningCeremonyRequestSignerListField>} 
     */
    constructor(docField, docNameField, loginPasswordField, loginUserNameField, signerListField) { 
        
        MultipleSignersSigningCeremonyRequest.initialize(this, docField, docNameField, loginPasswordField, loginUserNameField, signerListField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docField, docNameField, loginPasswordField, loginUserNameField, signerListField) { 
        obj['DocField'] = docField;
        obj['DocNameField'] = docNameField;
        obj['LoginPasswordField'] = loginPasswordField;
        obj['LoginUserNameField'] = loginUserNameField;
        obj['SignerListField'] = signerListField;
    }

    /**
     * Constructs a <code>MultipleSignersSigningCeremonyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MultipleSignersSigningCeremonyRequest} obj Optional instance to populate.
     * @return {module:model/MultipleSignersSigningCeremonyRequest} The populated <code>MultipleSignersSigningCeremonyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultipleSignersSigningCeremonyRequest();

            if (data.hasOwnProperty('DocField')) {
                obj['DocField'] = ApiClient.convertToType(data['DocField'], 'String');
            }
            if (data.hasOwnProperty('DocNameField')) {
                obj['DocNameField'] = ApiClient.convertToType(data['DocNameField'], 'String');
            }
            if (data.hasOwnProperty('LoginPasswordField')) {
                obj['LoginPasswordField'] = ApiClient.convertToType(data['LoginPasswordField'], 'String');
            }
            if (data.hasOwnProperty('LoginUserNameField')) {
                obj['LoginUserNameField'] = ApiClient.convertToType(data['LoginUserNameField'], 'String');
            }
            if (data.hasOwnProperty('SignerListField')) {
                obj['SignerListField'] = ApiClient.convertToType(data['SignerListField'], [MultipleSignersSigningCeremonyRequestSignerListField]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} DocField
 */
MultipleSignersSigningCeremonyRequest.prototype['DocField'] = undefined;

/**
 * @member {String} DocNameField
 */
MultipleSignersSigningCeremonyRequest.prototype['DocNameField'] = undefined;

/**
 * User's password.
 * @member {String} LoginPasswordField
 */
MultipleSignersSigningCeremonyRequest.prototype['LoginPasswordField'] = undefined;

/**
 * User's username.
 * @member {String} LoginUserNameField
 */
MultipleSignersSigningCeremonyRequest.prototype['LoginUserNameField'] = undefined;

/**
 * @member {Array.<module:model/MultipleSignersSigningCeremonyRequestSignerListField>} SignerListField
 */
MultipleSignersSigningCeremonyRequest.prototype['SignerListField'] = undefined;






export default MultipleSignersSigningCeremonyRequest;

