/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MultipleSignersSigningCeremonyRequestSignerListField model module.
 * @module model/MultipleSignersSigningCeremonyRequestSignerListField
 * @version 1.0.1
 */
class MultipleSignersSigningCeremonyRequestSignerListField {
    /**
     * Constructs a new <code>MultipleSignersSigningCeremonyRequestSignerListField</code>.
     * @alias module:model/MultipleSignersSigningCeremonyRequestSignerListField
     * @param signatureHField {Number} 
     * @param signatureImageField {String} 
     * @param signatureImageIncludeBorderField {Boolean} 
     * @param signatureImageIncludeReasonField {Boolean} 
     * @param signatureImageIncludeSignedByField {Boolean} 
     * @param signatureImageIncludeSignedDateField {Boolean} 
     * @param signatureImageTypeField {Number} 
     * @param signaturePageField {Number} 
     * @param signatureWField {Number} 
     * @param signatureXField {Number} 
     * @param signatureYField {Number} 
     * @param signerEmailField {String} 
     * @param signerFullNameField {String} 
     * @param signerIndentificationNumberField {String} 
     * @param signerLocationField {String} 
     * @param signerMobileNumberField {String} 
     * @param signerReasonField {String} 
     * @param signerTrustOriginField {String} 
     * @param signerTrustReferenceField {String} 
     */
    constructor(signatureHField, signatureImageField, signatureImageIncludeBorderField, signatureImageIncludeReasonField, signatureImageIncludeSignedByField, signatureImageIncludeSignedDateField, signatureImageTypeField, signaturePageField, signatureWField, signatureXField, signatureYField, signerEmailField, signerFullNameField, signerIndentificationNumberField, signerLocationField, signerMobileNumberField, signerReasonField, signerTrustOriginField, signerTrustReferenceField) { 
        
        MultipleSignersSigningCeremonyRequestSignerListField.initialize(this, signatureHField, signatureImageField, signatureImageIncludeBorderField, signatureImageIncludeReasonField, signatureImageIncludeSignedByField, signatureImageIncludeSignedDateField, signatureImageTypeField, signaturePageField, signatureWField, signatureXField, signatureYField, signerEmailField, signerFullNameField, signerIndentificationNumberField, signerLocationField, signerMobileNumberField, signerReasonField, signerTrustOriginField, signerTrustReferenceField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, signatureHField, signatureImageField, signatureImageIncludeBorderField, signatureImageIncludeReasonField, signatureImageIncludeSignedByField, signatureImageIncludeSignedDateField, signatureImageTypeField, signaturePageField, signatureWField, signatureXField, signatureYField, signerEmailField, signerFullNameField, signerIndentificationNumberField, signerLocationField, signerMobileNumberField, signerReasonField, signerTrustOriginField, signerTrustReferenceField) { 
        obj['SignatureHField'] = signatureHField;
        obj['SignatureImageField'] = signatureImageField;
        obj['SignatureImageIncludeBorderField'] = signatureImageIncludeBorderField;
        obj['SignatureImageIncludeReasonField'] = signatureImageIncludeReasonField;
        obj['SignatureImageIncludeSignedByField'] = signatureImageIncludeSignedByField;
        obj['SignatureImageIncludeSignedDateField'] = signatureImageIncludeSignedDateField;
        obj['SignatureImageTypeField'] = signatureImageTypeField;
        obj['SignaturePageField'] = signaturePageField;
        obj['SignatureWField'] = signatureWField;
        obj['SignatureXField'] = signatureXField;
        obj['SignatureYField'] = signatureYField;
        obj['SignerEmailField'] = signerEmailField;
        obj['SignerFullNameField'] = signerFullNameField;
        obj['SignerIndentificationNumberField'] = signerIndentificationNumberField;
        obj['SignerLocationField'] = signerLocationField;
        obj['SignerMobileNumberField'] = signerMobileNumberField;
        obj['SignerReasonField'] = signerReasonField;
        obj['SignerTrustOriginField'] = signerTrustOriginField;
        obj['SignerTrustReferenceField'] = signerTrustReferenceField;
    }

    /**
     * Constructs a <code>MultipleSignersSigningCeremonyRequestSignerListField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MultipleSignersSigningCeremonyRequestSignerListField} obj Optional instance to populate.
     * @return {module:model/MultipleSignersSigningCeremonyRequestSignerListField} The populated <code>MultipleSignersSigningCeremonyRequestSignerListField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultipleSignersSigningCeremonyRequestSignerListField();

            if (data.hasOwnProperty('SignatureHField')) {
                obj['SignatureHField'] = ApiClient.convertToType(data['SignatureHField'], 'Number');
            }
            if (data.hasOwnProperty('SignatureImageField')) {
                obj['SignatureImageField'] = ApiClient.convertToType(data['SignatureImageField'], 'String');
            }
            if (data.hasOwnProperty('SignatureImageIncludeBorderField')) {
                obj['SignatureImageIncludeBorderField'] = ApiClient.convertToType(data['SignatureImageIncludeBorderField'], 'Boolean');
            }
            if (data.hasOwnProperty('SignatureImageIncludeReasonField')) {
                obj['SignatureImageIncludeReasonField'] = ApiClient.convertToType(data['SignatureImageIncludeReasonField'], 'Boolean');
            }
            if (data.hasOwnProperty('SignatureImageIncludeSignedByField')) {
                obj['SignatureImageIncludeSignedByField'] = ApiClient.convertToType(data['SignatureImageIncludeSignedByField'], 'Boolean');
            }
            if (data.hasOwnProperty('SignatureImageIncludeSignedDateField')) {
                obj['SignatureImageIncludeSignedDateField'] = ApiClient.convertToType(data['SignatureImageIncludeSignedDateField'], 'Boolean');
            }
            if (data.hasOwnProperty('SignatureImageTypeField')) {
                obj['SignatureImageTypeField'] = ApiClient.convertToType(data['SignatureImageTypeField'], 'Number');
            }
            if (data.hasOwnProperty('SignaturePageField')) {
                obj['SignaturePageField'] = ApiClient.convertToType(data['SignaturePageField'], 'Number');
            }
            if (data.hasOwnProperty('SignatureWField')) {
                obj['SignatureWField'] = ApiClient.convertToType(data['SignatureWField'], 'Number');
            }
            if (data.hasOwnProperty('SignatureXField')) {
                obj['SignatureXField'] = ApiClient.convertToType(data['SignatureXField'], 'Number');
            }
            if (data.hasOwnProperty('SignatureYField')) {
                obj['SignatureYField'] = ApiClient.convertToType(data['SignatureYField'], 'Number');
            }
            if (data.hasOwnProperty('SignerEmailField')) {
                obj['SignerEmailField'] = ApiClient.convertToType(data['SignerEmailField'], 'String');
            }
            if (data.hasOwnProperty('SignerFullNameField')) {
                obj['SignerFullNameField'] = ApiClient.convertToType(data['SignerFullNameField'], 'String');
            }
            if (data.hasOwnProperty('SignerIndentificationNumberField')) {
                obj['SignerIndentificationNumberField'] = ApiClient.convertToType(data['SignerIndentificationNumberField'], 'String');
            }
            if (data.hasOwnProperty('SignerLocationField')) {
                obj['SignerLocationField'] = ApiClient.convertToType(data['SignerLocationField'], 'String');
            }
            if (data.hasOwnProperty('SignerMobileNumberField')) {
                obj['SignerMobileNumberField'] = ApiClient.convertToType(data['SignerMobileNumberField'], 'String');
            }
            if (data.hasOwnProperty('SignerReasonField')) {
                obj['SignerReasonField'] = ApiClient.convertToType(data['SignerReasonField'], 'String');
            }
            if (data.hasOwnProperty('SignerTrustOriginField')) {
                obj['SignerTrustOriginField'] = ApiClient.convertToType(data['SignerTrustOriginField'], 'String');
            }
            if (data.hasOwnProperty('SignerTrustReferenceField')) {
                obj['SignerTrustReferenceField'] = ApiClient.convertToType(data['SignerTrustReferenceField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} SignatureHField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureHField'] = undefined;

/**
 * @member {String} SignatureImageField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureImageField'] = undefined;

/**
 * @member {Boolean} SignatureImageIncludeBorderField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureImageIncludeBorderField'] = undefined;

/**
 * @member {Boolean} SignatureImageIncludeReasonField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureImageIncludeReasonField'] = undefined;

/**
 * @member {Boolean} SignatureImageIncludeSignedByField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureImageIncludeSignedByField'] = undefined;

/**
 * @member {Boolean} SignatureImageIncludeSignedDateField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureImageIncludeSignedDateField'] = undefined;

/**
 * @member {Number} SignatureImageTypeField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureImageTypeField'] = undefined;

/**
 * @member {Number} SignaturePageField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignaturePageField'] = undefined;

/**
 * @member {Number} SignatureWField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureWField'] = undefined;

/**
 * @member {Number} SignatureXField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureXField'] = undefined;

/**
 * @member {Number} SignatureYField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignatureYField'] = undefined;

/**
 * @member {String} SignerEmailField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerEmailField'] = undefined;

/**
 * @member {String} SignerFullNameField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerFullNameField'] = undefined;

/**
 * @member {String} SignerIndentificationNumberField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerIndentificationNumberField'] = undefined;

/**
 * @member {String} SignerLocationField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerLocationField'] = undefined;

/**
 * @member {String} SignerMobileNumberField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerMobileNumberField'] = undefined;

/**
 * @member {String} SignerReasonField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerReasonField'] = undefined;

/**
 * @member {String} SignerTrustOriginField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerTrustOriginField'] = undefined;

/**
 * @member {String} SignerTrustReferenceField
 */
MultipleSignersSigningCeremonyRequestSignerListField.prototype['SignerTrustReferenceField'] = undefined;






export default MultipleSignersSigningCeremonyRequestSignerListField;

