/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The SetDocumentOrderRequest model module.
 * @module model/SetDocumentOrderRequest
 * @version 1.0.1
 */
class SetDocumentOrderRequest {
    /**
     * Constructs a new <code>SetDocumentOrderRequest</code>.
     * #### The request sent when the document order for signing is confirmed.
     * @alias module:model/SetDocumentOrderRequest
     * @param docIDField {String} 
     * @param documentOrderField {String} 
     * @param tokenField {module:model/TokenField} 
     */
    constructor(docIDField, documentOrderField, tokenField) { 
        
        SetDocumentOrderRequest.initialize(this, docIDField, documentOrderField, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, documentOrderField, tokenField) { 
        obj['DocIDField'] = docIDField;
        obj['DocumentOrderField'] = documentOrderField;
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>SetDocumentOrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetDocumentOrderRequest} obj Optional instance to populate.
     * @return {module:model/SetDocumentOrderRequest} The populated <code>SetDocumentOrderRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetDocumentOrderRequest();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'String');
            }
            if (data.hasOwnProperty('DocumentOrderField')) {
                obj['DocumentOrderField'] = ApiClient.convertToType(data['DocumentOrderField'], 'String');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} DocIDField
 */
SetDocumentOrderRequest.prototype['DocIDField'] = undefined;

/**
 * @member {String} DocumentOrderField
 */
SetDocumentOrderRequest.prototype['DocumentOrderField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
SetDocumentOrderRequest.prototype['TokenField'] = undefined;






export default SetDocumentOrderRequest;

