/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SharePortfolioResponse model module.
 * @module model/SharePortfolioResponse
 * @version 1.0.1
 */
class SharePortfolioResponse {
    /**
     * Constructs a new <code>SharePortfolioResponse</code>.
     * #### The response returned when a user wants to share a portfolio.
     * @alias module:model/SharePortfolioResponse
     * @param resultField {String} Displays the result of the call.
     */
    constructor(resultField) { 
        
        SharePortfolioResponse.initialize(this, resultField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resultField) { 
        obj['ResultField'] = resultField;
    }

    /**
     * Constructs a <code>SharePortfolioResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SharePortfolioResponse} obj Optional instance to populate.
     * @return {module:model/SharePortfolioResponse} The populated <code>SharePortfolioResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SharePortfolioResponse();

            if (data.hasOwnProperty('ResultField')) {
                obj['ResultField'] = ApiClient.convertToType(data['ResultField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Displays the result of the call.
 * @member {String} ResultField
 */
SharePortfolioResponse.prototype['ResultField'] = undefined;






export default SharePortfolioResponse;

