/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenField model module.
 * @module model/TokenField
 * @version 1.0.1
 */
class TokenField {
    /**
     * Constructs a new <code>TokenField</code>.
     * #### Authentication Token
     * @alias module:model/TokenField
     * @param tokenField {String} User API Token
     */
    constructor(tokenField) { 
        
        TokenField.initialize(this, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tokenField) { 
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>TokenField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenField} obj Optional instance to populate.
     * @return {module:model/TokenField} The populated <code>TokenField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenField();

            if (data.hasOwnProperty('TokenExpiryField')) {
                obj['TokenExpiryField'] = ApiClient.convertToType(data['TokenExpiryField'], 'Date');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = ApiClient.convertToType(data['TokenField'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Expiry date of Token
 * @member {Date} TokenExpiryField
 */
TokenField.prototype['TokenExpiryField'] = undefined;

/**
 * User API Token
 * @member {String} TokenField
 */
TokenField.prototype['TokenField'] = undefined;






export default TokenField;

