/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenField from './TokenField';

/**
 * The WorkflowSignRequest model module.
 * @module model/WorkflowSignRequest
 * @version 1.0.1
 */
class WorkflowSignRequest {
    /**
     * Constructs a new <code>WorkflowSignRequest</code>.
     * #### This request is sent when a document workflow needs to be signed.
     * @alias module:model/WorkflowSignRequest
     * @param docIDField {String} 
     * @param latitudeField {String} 
     * @param loginPasswordField {String} 
     * @param loginUserNameField {String} 
     * @param longitudeField {String} 
     * @param signReasonField {String} 
     * @param timeZoneOffsetField {Number} 
     * @param tokenField {module:model/TokenField} 
     */
    constructor(docIDField, latitudeField, loginPasswordField, loginUserNameField, longitudeField, signReasonField, timeZoneOffsetField, tokenField) { 
        
        WorkflowSignRequest.initialize(this, docIDField, latitudeField, loginPasswordField, loginUserNameField, longitudeField, signReasonField, timeZoneOffsetField, tokenField);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, docIDField, latitudeField, loginPasswordField, loginUserNameField, longitudeField, signReasonField, timeZoneOffsetField, tokenField) { 
        obj['DocIDField'] = docIDField;
        obj['LatitudeField'] = latitudeField;
        obj['LoginPasswordField'] = loginPasswordField;
        obj['LoginUserNameField'] = loginUserNameField;
        obj['LongitudeField'] = longitudeField;
        obj['SignReasonField'] = signReasonField;
        obj['TimeZoneOffsetField'] = timeZoneOffsetField;
        obj['TokenField'] = tokenField;
    }

    /**
     * Constructs a <code>WorkflowSignRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowSignRequest} obj Optional instance to populate.
     * @return {module:model/WorkflowSignRequest} The populated <code>WorkflowSignRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowSignRequest();

            if (data.hasOwnProperty('DocIDField')) {
                obj['DocIDField'] = ApiClient.convertToType(data['DocIDField'], 'String');
            }
            if (data.hasOwnProperty('LatitudeField')) {
                obj['LatitudeField'] = ApiClient.convertToType(data['LatitudeField'], 'String');
            }
            if (data.hasOwnProperty('LoginPasswordField')) {
                obj['LoginPasswordField'] = ApiClient.convertToType(data['LoginPasswordField'], 'String');
            }
            if (data.hasOwnProperty('LoginUserNameField')) {
                obj['LoginUserNameField'] = ApiClient.convertToType(data['LoginUserNameField'], 'String');
            }
            if (data.hasOwnProperty('LongitudeField')) {
                obj['LongitudeField'] = ApiClient.convertToType(data['LongitudeField'], 'String');
            }
            if (data.hasOwnProperty('SignReasonField')) {
                obj['SignReasonField'] = ApiClient.convertToType(data['SignReasonField'], 'String');
            }
            if (data.hasOwnProperty('TimeZoneOffsetField')) {
                obj['TimeZoneOffsetField'] = ApiClient.convertToType(data['TimeZoneOffsetField'], 'Number');
            }
            if (data.hasOwnProperty('TokenField')) {
                obj['TokenField'] = TokenField.constructFromObject(data['TokenField']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} DocIDField
 */
WorkflowSignRequest.prototype['DocIDField'] = undefined;

/**
 * @member {String} LatitudeField
 */
WorkflowSignRequest.prototype['LatitudeField'] = undefined;

/**
 * @member {String} LoginPasswordField
 */
WorkflowSignRequest.prototype['LoginPasswordField'] = undefined;

/**
 * @member {String} LoginUserNameField
 */
WorkflowSignRequest.prototype['LoginUserNameField'] = undefined;

/**
 * @member {String} LongitudeField
 */
WorkflowSignRequest.prototype['LongitudeField'] = undefined;

/**
 * @member {String} SignReasonField
 */
WorkflowSignRequest.prototype['SignReasonField'] = undefined;

/**
 * @member {Number} TimeZoneOffsetField
 */
WorkflowSignRequest.prototype['TimeZoneOffsetField'] = undefined;

/**
 * @member {module:model/TokenField} TokenField
 */
WorkflowSignRequest.prototype['TokenField'] = undefined;






export default WorkflowSignRequest;

