/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SigniFlowConnect);
  }
}(this, function(expect, SigniFlowConnect) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocPrepperAddFieldsFlowIDRequest', function() {
    it('should create an instance of DocPrepperAddFieldsFlowIDRequest', function() {
      // uncomment below and update the code to test DocPrepperAddFieldsFlowIDRequest
      //var instane = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be.a(SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest);
    });

    it('should have the property docFieldTypeField (base name: "DocFieldTypeField")', function() {
      // uncomment below and update the code to test the property docFieldTypeField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property docIDField (base name: "DocIDField")', function() {
      // uncomment below and update the code to test the property docIDField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property flowIDField (base name: "FlowIDField")', function() {
      // uncomment below and update the code to test the property flowIDField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property heightField (base name: "HeightField")', function() {
      // uncomment below and update the code to test the property heightField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property widthField (base name: "WidthField")', function() {
      // uncomment below and update the code to test the property widthField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property isInvisibleField (base name: "IsInvisibleField")', function() {
      // uncomment below and update the code to test the property isInvisibleField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property linkToField (base name: "LinkToField")', function() {
      // uncomment below and update the code to test the property linkToField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property pageNumberField (base name: "PageNumberField")', function() {
      // uncomment below and update the code to test the property pageNumberField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property nameField (base name: "NameField")', function() {
      // uncomment below and update the code to test the property nameField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property userEmailField (base name: "UserEmailField")', function() {
      // uncomment below and update the code to test the property userEmailField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property xCoordinateField (base name: "XCoordinateField")', function() {
      // uncomment below and update the code to test the property xCoordinateField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property yCoordinateField (base name: "YCoordinateField")', function() {
      // uncomment below and update the code to test the property yCoordinateField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

    it('should have the property tokenField (base name: "TokenField")', function() {
      // uncomment below and update the code to test the property tokenField
      //var instance = new SigniFlowConnect.DocPrepperAddFieldsFlowIDRequest();
      //expect(instance).to.be();
    });

  });

}));
