/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SigniFlowConnect);
  }
}(this, function(expect, SigniFlowConnect) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SigniFlowConnect.FullWorkflowRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FullWorkflowRequest', function() {
    it('should create an instance of FullWorkflowRequest', function() {
      // uncomment below and update the code to test FullWorkflowRequest
      //var instane = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be.a(SigniFlowConnect.FullWorkflowRequest);
    });

    it('should have the property additionalDataField (base name: "AdditionalDataField")', function() {
      // uncomment below and update the code to test the property additionalDataField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property autoRemindField (base name: "AutoRemindField")', function() {
      // uncomment below and update the code to test the property autoRemindField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property customMessageField (base name: "CustomMessageField")', function() {
      // uncomment below and update the code to test the property customMessageField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property docField (base name: "DocField")', function() {
      // uncomment below and update the code to test the property docField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property docNameField (base name: "DocNameField")', function() {
      // uncomment below and update the code to test the property docNameField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property dueDateField (base name: "DueDateField")', function() {
      // uncomment below and update the code to test the property dueDateField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property extensionField (base name: "ExtensionField")', function() {
      // uncomment below and update the code to test the property extensionField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property flattenDocumentField (base name: "FlattenDocumentField")', function() {
      // uncomment below and update the code to test the property flattenDocumentField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property keepContentSecurityField (base name: "KeepContentSecurityField")', function() {
      // uncomment below and update the code to test the property keepContentSecurityField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property keepCustomPropertiesField (base name: "KeepCustomPropertiesField")', function() {
      // uncomment below and update the code to test the property keepCustomPropertiesField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property keepXMPMetadataField (base name: "KeepXMPMetadataField")', function() {
      // uncomment below and update the code to test the property keepXMPMetadataField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property portfolioInformationField (base name: "PortfolioInformationField")', function() {
      // uncomment below and update the code to test the property portfolioInformationField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property priorityField (base name: "PriorityField")', function() {
      // uncomment below and update the code to test the property priorityField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property sLAField (base name: "SLAField")', function() {
      // uncomment below and update the code to test the property sLAField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property sendFirstEmailField (base name: "SendFirstEmailField")', function() {
      // uncomment below and update the code to test the property sendFirstEmailField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property sendWorkflowEmailsField (base name: "SendWorkflowEmailsField")', function() {
      // uncomment below and update the code to test the property sendWorkflowEmailsField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property tokenField (base name: "TokenField")', function() {
      // uncomment below and update the code to test the property tokenField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

    it('should have the property workflowUsersListField (base name: "WorkflowUsersListField")', function() {
      // uncomment below and update the code to test the property workflowUsersListField
      //var instance = new SigniFlowConnect.FullWorkflowRequest();
      //expect(instance).to.be();
    });

  });

}));
