/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SigniFlowConnect);
  }
}(this, function(expect, SigniFlowConnect) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FullWorkflowRequestWorkflowUsersListField', function() {
    it('should create an instance of FullWorkflowRequestWorkflowUsersListField', function() {
      // uncomment below and update the code to test FullWorkflowRequestWorkflowUsersListField
      //var instane = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be.a(SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField);
    });

    it('should have the property actionField (base name: "ActionField")', function() {
      // uncomment below and update the code to test the property actionField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property allowProxyField (base name: "AllowProxyField")', function() {
      // uncomment below and update the code to test the property allowProxyField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property autoSignField (base name: "AutoSignField")', function() {
      // uncomment below and update the code to test the property autoSignField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property emailAddressField (base name: "EmailAddressField")', function() {
      // uncomment below and update the code to test the property emailAddressField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property groupStepField (base name: "GroupStepField")', function() {
      // uncomment below and update the code to test the property groupStepField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property languageCodeField (base name: "LanguageCodeField")', function() {
      // uncomment below and update the code to test the property languageCodeField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property latitudeField (base name: "LatitudeField")', function() {
      // uncomment below and update the code to test the property latitudeField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property longitudeField (base name: "LongitudeField")', function() {
      // uncomment below and update the code to test the property longitudeField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property mobileNumberField (base name: "MobileNumberField")', function() {
      // uncomment below and update the code to test the property mobileNumberField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property preloadedFaceToFaceSignersField (base name: "PreloadedFaceToFaceSignersField")', function() {
      // uncomment below and update the code to test the property preloadedFaceToFaceSignersField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property signReasonField (base name: "SignReasonField")', function() {
      // uncomment below and update the code to test the property signReasonField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property signerPasswordField (base name: "SignerPasswordField")', function() {
      // uncomment below and update the code to test the property signerPasswordField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property userFirstNameField (base name: "UserFirstNameField")', function() {
      // uncomment below and update the code to test the property userFirstNameField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property userFullNameField (base name: "UserFullNameField")', function() {
      // uncomment below and update the code to test the property userFullNameField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property userLastNameField (base name: "UserLastNameField")', function() {
      // uncomment below and update the code to test the property userLastNameField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

    it('should have the property workflowUserFieldsField (base name: "WorkflowUserFieldsField")', function() {
      // uncomment below and update the code to test the property workflowUserFieldsField
      //var instance = new SigniFlowConnect.FullWorkflowRequestWorkflowUsersListField();
      //expect(instance).to.be();
    });

  });

}));
