/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SigniFlowConnect);
  }
}(this, function(expect, SigniFlowConnect) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SigniFlowConnect.FullWorkflowRequestGroupStepFieldGroupMembersField();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FullWorkflowRequestGroupStepFieldGroupMembersField', function() {
    it('should create an instance of FullWorkflowRequestGroupStepFieldGroupMembersField', function() {
      // uncomment below and update the code to test FullWorkflowRequestGroupStepFieldGroupMembersField
      //var instane = new SigniFlowConnect.FullWorkflowRequestGroupStepFieldGroupMembersField();
      //expect(instance).to.be.a(SigniFlowConnect.FullWorkflowRequestGroupStepFieldGroupMembersField);
    });

    it('should have the property languageCodeField (base name: "LanguageCodeField")', function() {
      // uncomment below and update the code to test the property languageCodeField
      //var instance = new SigniFlowConnect.FullWorkflowRequestGroupStepFieldGroupMembersField();
      //expect(instance).to.be();
    });

    it('should have the property userEmailField (base name: "UserEmailField")', function() {
      // uncomment below and update the code to test the property userEmailField
      //var instance = new SigniFlowConnect.FullWorkflowRequestGroupStepFieldGroupMembersField();
      //expect(instance).to.be();
    });

    it('should have the property userFullNameField (base name: "UserFullNameField")', function() {
      // uncomment below and update the code to test the property userFullNameField
      //var instance = new SigniFlowConnect.FullWorkflowRequestGroupStepFieldGroupMembersField();
      //expect(instance).to.be();
    });

    it('should have the property userMobileNumberField (base name: "UserMobileNumberField")', function() {
      // uncomment below and update the code to test the property userMobileNumberField
      //var instance = new SigniFlowConnect.FullWorkflowRequestGroupStepFieldGroupMembersField();
      //expect(instance).to.be();
    });

  });

}));
