/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SigniFlowConnect);
  }
}(this, function(expect, SigniFlowConnect) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MultipleSignersSigningCeremonyRequestSignerListField', function() {
    it('should create an instance of MultipleSignersSigningCeremonyRequestSignerListField', function() {
      // uncomment below and update the code to test MultipleSignersSigningCeremonyRequestSignerListField
      //var instane = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be.a(SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField);
    });

    it('should have the property signatureHField (base name: "SignatureHField")', function() {
      // uncomment below and update the code to test the property signatureHField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureImageField (base name: "SignatureImageField")', function() {
      // uncomment below and update the code to test the property signatureImageField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureImageIncludeBorderField (base name: "SignatureImageIncludeBorderField")', function() {
      // uncomment below and update the code to test the property signatureImageIncludeBorderField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureImageIncludeReasonField (base name: "SignatureImageIncludeReasonField")', function() {
      // uncomment below and update the code to test the property signatureImageIncludeReasonField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureImageIncludeSignedByField (base name: "SignatureImageIncludeSignedByField")', function() {
      // uncomment below and update the code to test the property signatureImageIncludeSignedByField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureImageIncludeSignedDateField (base name: "SignatureImageIncludeSignedDateField")', function() {
      // uncomment below and update the code to test the property signatureImageIncludeSignedDateField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureImageTypeField (base name: "SignatureImageTypeField")', function() {
      // uncomment below and update the code to test the property signatureImageTypeField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signaturePageField (base name: "SignaturePageField")', function() {
      // uncomment below and update the code to test the property signaturePageField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureWField (base name: "SignatureWField")', function() {
      // uncomment below and update the code to test the property signatureWField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureXField (base name: "SignatureXField")', function() {
      // uncomment below and update the code to test the property signatureXField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signatureYField (base name: "SignatureYField")', function() {
      // uncomment below and update the code to test the property signatureYField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerEmailField (base name: "SignerEmailField")', function() {
      // uncomment below and update the code to test the property signerEmailField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerFullNameField (base name: "SignerFullNameField")', function() {
      // uncomment below and update the code to test the property signerFullNameField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerIndentificationNumberField (base name: "SignerIndentificationNumberField")', function() {
      // uncomment below and update the code to test the property signerIndentificationNumberField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerLocationField (base name: "SignerLocationField")', function() {
      // uncomment below and update the code to test the property signerLocationField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerMobileNumberField (base name: "SignerMobileNumberField")', function() {
      // uncomment below and update the code to test the property signerMobileNumberField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerReasonField (base name: "SignerReasonField")', function() {
      // uncomment below and update the code to test the property signerReasonField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerTrustOriginField (base name: "SignerTrustOriginField")', function() {
      // uncomment below and update the code to test the property signerTrustOriginField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

    it('should have the property signerTrustReferenceField (base name: "SignerTrustReferenceField")', function() {
      // uncomment below and update the code to test the property signerTrustReferenceField
      //var instance = new SigniFlowConnect.MultipleSignersSigningCeremonyRequestSignerListField();
      //expect(instance).to.be();
    });

  });

}));
