/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ActionField from './model/ActionField';
import AddWokflowStepV2Response from './model/AddWokflowStepV2Response';
import AddWokflowStepV2ResponseFlowStepsField from './model/AddWokflowStepV2ResponseFlowStepsField';
import AddWorkflowStepV2Request from './model/AddWorkflowStepV2Request';
import AdvancedFieldType from './model/AdvancedFieldType';
import ApplyPrepperTemplateRequest from './model/ApplyPrepperTemplateRequest';
import ApplyPrepperTemplateResponse from './model/ApplyPrepperTemplateResponse';
import AutoExpire from './model/AutoExpire';
import AutoRemind from './model/AutoRemind';
import CancelFlowRequest from './model/CancelFlowRequest';
import CancelFlowResponse from './model/CancelFlowResponse';
import CreatePortfolioRequest from './model/CreatePortfolioRequest';
import CreatePortfolioResponse from './model/CreatePortfolioResponse';
import CreateWorkflowRequest from './model/CreateWorkflowRequest';
import CreateWorkflowResponse from './model/CreateWorkflowResponse';
import DeleteDocRequest from './model/DeleteDocRequest';
import DeleteDocResponse from './model/DeleteDocResponse';
import DocExtension from './model/DocExtension';
import DocPrepperAddAdvancedFieldsRequest from './model/DocPrepperAddAdvancedFieldsRequest';
import DocPrepperAddAdvancedFieldsRequestFieldInfoListField from './model/DocPrepperAddAdvancedFieldsRequestFieldInfoListField';
import DocPrepperAddAdvancedFieldsRequestFieldOptionsListField from './model/DocPrepperAddAdvancedFieldsRequestFieldOptionsListField';
import DocPrepperAddAdvancedFieldsResponse from './model/DocPrepperAddAdvancedFieldsResponse';
import DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField from './model/DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField';
import DocPrepperAddFieldsFlowIDRequest from './model/DocPrepperAddFieldsFlowIDRequest';
import DocPrepperAddFieldsFlowIDResponse from './model/DocPrepperAddFieldsFlowIDResponse';
import DownloadPortfolioRequest from './model/DownloadPortfolioRequest';
import DownloadPortfolioResponse from './model/DownloadPortfolioResponse';
import FieldType from './model/FieldType';
import FullWorkflowRequest from './model/FullWorkflowRequest';
import FullWorkflowRequestGroupStepField from './model/FullWorkflowRequestGroupStepField';
import FullWorkflowRequestGroupStepFieldGroupMembersField from './model/FullWorkflowRequestGroupStepFieldGroupMembersField';
import FullWorkflowRequestPortfolioInformationField from './model/FullWorkflowRequestPortfolioInformationField';
import FullWorkflowRequestWorkflowUserFieldsField from './model/FullWorkflowRequestWorkflowUserFieldsField';
import FullWorkflowRequestWorkflowUsersListField from './model/FullWorkflowRequestWorkflowUsersListField';
import FullWorkflowResponse from './model/FullWorkflowResponse';
import GetAuditDocumentRequest from './model/GetAuditDocumentRequest';
import GetAuditDocumentResponse from './model/GetAuditDocumentResponse';
import GetDocLinkRequest from './model/GetDocLinkRequest';
import GetDocLinkResponse from './model/GetDocLinkResponse';
import GetDocStatusRequest from './model/GetDocStatusRequest';
import GetDocStatusResponse from './model/GetDocStatusResponse';
import GetDocumentAuditRequest from './model/GetDocumentAuditRequest';
import GetDocumentAuditResponse from './model/GetDocumentAuditResponse';
import GetDocumentAuditResponseActivityField from './model/GetDocumentAuditResponseActivityField';
import GetDocumentPrepperLinkRequest from './model/GetDocumentPrepperLinkRequest';
import GetDocumentPrepperLinkResponse from './model/GetDocumentPrepperLinkResponse';
import GetDocumentRequest from './model/GetDocumentRequest';
import GetDocumentResponse from './model/GetDocumentResponse';
import GetDocumentTagFieldBoxPositionRequest from './model/GetDocumentTagFieldBoxPositionRequest';
import GetDocumentTagFieldBoxPositionResponse from './model/GetDocumentTagFieldBoxPositionResponse';
import GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField from './model/GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField';
import GetDocumentTagFieldPositionRequest from './model/GetDocumentTagFieldPositionRequest';
import GetDocumentTagFieldPositionResponse from './model/GetDocumentTagFieldPositionResponse';
import GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField from './model/GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField';
import GetPrepperTemplateListRequest from './model/GetPrepperTemplateListRequest';
import GetPrepperTemplateListResponse from './model/GetPrepperTemplateListResponse';
import GetPrepperTemplateListResponseTemplateInformationValuesField from './model/GetPrepperTemplateListResponseTemplateInformationValuesField';
import GetPrepperTemplateRequest from './model/GetPrepperTemplateRequest';
import GetPrepperTemplateResponse from './model/GetPrepperTemplateResponse';
import GetPrepperTemplateResponsePrepperTemplateValuesField from './model/GetPrepperTemplateResponsePrepperTemplateValuesField';
import InitiateFlowNoEmailRequest from './model/InitiateFlowNoEmailRequest';
import InitiateFlowNoEmailResponse from './model/InitiateFlowNoEmailResponse';
import InitiateFlowNoInitialEmailRequest from './model/InitiateFlowNoInitialEmailRequest';
import InitiateFlowNoInitialEmailResponse from './model/InitiateFlowNoInitialEmailResponse';
import InitiateFlowRequest from './model/InitiateFlowRequest';
import InitiateFlowResponse from './model/InitiateFlowResponse';
import LinkToPortfolioRequest from './model/LinkToPortfolioRequest';
import LinkToPortfolioResponse from './model/LinkToPortfolioResponse';
import LoginRequest from './model/LoginRequest';
import LoginResponse from './model/LoginResponse';
import LogoutRequest from './model/LogoutRequest';
import LogoutResponse from './model/LogoutResponse';
import MultipleSignersSigningCeremonyRequest from './model/MultipleSignersSigningCeremonyRequest';
import MultipleSignersSigningCeremonyRequestSignerListField from './model/MultipleSignersSigningCeremonyRequestSignerListField';
import MultipleSignersSigningCeremonyResponse from './model/MultipleSignersSigningCeremonyResponse';
import Priority from './model/Priority';
import ProxyAllowedField from './model/ProxyAllowedField';
import SetDocumentOrderRequest from './model/SetDocumentOrderRequest';
import SetDocumentOrderResponse from './model/SetDocumentOrderResponse';
import SharePortfolioNoEmailRequest from './model/SharePortfolioNoEmailRequest';
import SharePortfolioNoEmailResponse from './model/SharePortfolioNoEmailResponse';
import SharePortfolioRequest from './model/SharePortfolioRequest';
import SharePortfolioResponse from './model/SharePortfolioResponse';
import SigningCeremonyV2Request from './model/SigningCeremonyV2Request';
import SigningCeremonyV2Response from './model/SigningCeremonyV2Response';
import TokenExtendRequest from './model/TokenExtendRequest';
import TokenExtendResponse from './model/TokenExtendResponse';
import TokenField from './model/TokenField';
import TokenValidateRequest from './model/TokenValidateRequest';
import TokenValidateResponse from './model/TokenValidateResponse';
import WorkflowSignRequest from './model/WorkflowSignRequest';
import WorkflowSignResponse from './model/WorkflowSignResponse';
import AuditsApi from './api/AuditsApi';
import AuthenticationApi from './api/AuthenticationApi';
import PortfoliosApi from './api/PortfoliosApi';
import SigningCeremonyApi from './api/SigningCeremonyApi';
import TemplatesApi from './api/TemplatesApi';
import ViewersApi from './api/ViewersApi';
import WorkFlowApi from './api/WorkFlowApi';


/**
* JavaScript client library for the SigniFlow Connect v1 API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SigniFlowConnect = require('index'); // See note below*.
* var xxxSvc = new SigniFlowConnect.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SigniFlowConnect.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SigniFlowConnect.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SigniFlowConnect.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ActionField model constructor.
     * @property {module:model/ActionField}
     */
    ActionField,

    /**
     * The AddWokflowStepV2Response model constructor.
     * @property {module:model/AddWokflowStepV2Response}
     */
    AddWokflowStepV2Response,

    /**
     * The AddWokflowStepV2ResponseFlowStepsField model constructor.
     * @property {module:model/AddWokflowStepV2ResponseFlowStepsField}
     */
    AddWokflowStepV2ResponseFlowStepsField,

    /**
     * The AddWorkflowStepV2Request model constructor.
     * @property {module:model/AddWorkflowStepV2Request}
     */
    AddWorkflowStepV2Request,

    /**
     * The AdvancedFieldType model constructor.
     * @property {module:model/AdvancedFieldType}
     */
    AdvancedFieldType,

    /**
     * The ApplyPrepperTemplateRequest model constructor.
     * @property {module:model/ApplyPrepperTemplateRequest}
     */
    ApplyPrepperTemplateRequest,

    /**
     * The ApplyPrepperTemplateResponse model constructor.
     * @property {module:model/ApplyPrepperTemplateResponse}
     */
    ApplyPrepperTemplateResponse,

    /**
     * The AutoExpire model constructor.
     * @property {module:model/AutoExpire}
     */
    AutoExpire,

    /**
     * The AutoRemind model constructor.
     * @property {module:model/AutoRemind}
     */
    AutoRemind,

    /**
     * The CancelFlowRequest model constructor.
     * @property {module:model/CancelFlowRequest}
     */
    CancelFlowRequest,

    /**
     * The CancelFlowResponse model constructor.
     * @property {module:model/CancelFlowResponse}
     */
    CancelFlowResponse,

    /**
     * The CreatePortfolioRequest model constructor.
     * @property {module:model/CreatePortfolioRequest}
     */
    CreatePortfolioRequest,

    /**
     * The CreatePortfolioResponse model constructor.
     * @property {module:model/CreatePortfolioResponse}
     */
    CreatePortfolioResponse,

    /**
     * The CreateWorkflowRequest model constructor.
     * @property {module:model/CreateWorkflowRequest}
     */
    CreateWorkflowRequest,

    /**
     * The CreateWorkflowResponse model constructor.
     * @property {module:model/CreateWorkflowResponse}
     */
    CreateWorkflowResponse,

    /**
     * The DeleteDocRequest model constructor.
     * @property {module:model/DeleteDocRequest}
     */
    DeleteDocRequest,

    /**
     * The DeleteDocResponse model constructor.
     * @property {module:model/DeleteDocResponse}
     */
    DeleteDocResponse,

    /**
     * The DocExtension model constructor.
     * @property {module:model/DocExtension}
     */
    DocExtension,

    /**
     * The DocPrepperAddAdvancedFieldsRequest model constructor.
     * @property {module:model/DocPrepperAddAdvancedFieldsRequest}
     */
    DocPrepperAddAdvancedFieldsRequest,

    /**
     * The DocPrepperAddAdvancedFieldsRequestFieldInfoListField model constructor.
     * @property {module:model/DocPrepperAddAdvancedFieldsRequestFieldInfoListField}
     */
    DocPrepperAddAdvancedFieldsRequestFieldInfoListField,

    /**
     * The DocPrepperAddAdvancedFieldsRequestFieldOptionsListField model constructor.
     * @property {module:model/DocPrepperAddAdvancedFieldsRequestFieldOptionsListField}
     */
    DocPrepperAddAdvancedFieldsRequestFieldOptionsListField,

    /**
     * The DocPrepperAddAdvancedFieldsResponse model constructor.
     * @property {module:model/DocPrepperAddAdvancedFieldsResponse}
     */
    DocPrepperAddAdvancedFieldsResponse,

    /**
     * The DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField model constructor.
     * @property {module:model/DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField}
     */
    DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField,

    /**
     * The DocPrepperAddFieldsFlowIDRequest model constructor.
     * @property {module:model/DocPrepperAddFieldsFlowIDRequest}
     */
    DocPrepperAddFieldsFlowIDRequest,

    /**
     * The DocPrepperAddFieldsFlowIDResponse model constructor.
     * @property {module:model/DocPrepperAddFieldsFlowIDResponse}
     */
    DocPrepperAddFieldsFlowIDResponse,

    /**
     * The DownloadPortfolioRequest model constructor.
     * @property {module:model/DownloadPortfolioRequest}
     */
    DownloadPortfolioRequest,

    /**
     * The DownloadPortfolioResponse model constructor.
     * @property {module:model/DownloadPortfolioResponse}
     */
    DownloadPortfolioResponse,

    /**
     * The FieldType model constructor.
     * @property {module:model/FieldType}
     */
    FieldType,

    /**
     * The FullWorkflowRequest model constructor.
     * @property {module:model/FullWorkflowRequest}
     */
    FullWorkflowRequest,

    /**
     * The FullWorkflowRequestGroupStepField model constructor.
     * @property {module:model/FullWorkflowRequestGroupStepField}
     */
    FullWorkflowRequestGroupStepField,

    /**
     * The FullWorkflowRequestGroupStepFieldGroupMembersField model constructor.
     * @property {module:model/FullWorkflowRequestGroupStepFieldGroupMembersField}
     */
    FullWorkflowRequestGroupStepFieldGroupMembersField,

    /**
     * The FullWorkflowRequestPortfolioInformationField model constructor.
     * @property {module:model/FullWorkflowRequestPortfolioInformationField}
     */
    FullWorkflowRequestPortfolioInformationField,

    /**
     * The FullWorkflowRequestWorkflowUserFieldsField model constructor.
     * @property {module:model/FullWorkflowRequestWorkflowUserFieldsField}
     */
    FullWorkflowRequestWorkflowUserFieldsField,

    /**
     * The FullWorkflowRequestWorkflowUsersListField model constructor.
     * @property {module:model/FullWorkflowRequestWorkflowUsersListField}
     */
    FullWorkflowRequestWorkflowUsersListField,

    /**
     * The FullWorkflowResponse model constructor.
     * @property {module:model/FullWorkflowResponse}
     */
    FullWorkflowResponse,

    /**
     * The GetAuditDocumentRequest model constructor.
     * @property {module:model/GetAuditDocumentRequest}
     */
    GetAuditDocumentRequest,

    /**
     * The GetAuditDocumentResponse model constructor.
     * @property {module:model/GetAuditDocumentResponse}
     */
    GetAuditDocumentResponse,

    /**
     * The GetDocLinkRequest model constructor.
     * @property {module:model/GetDocLinkRequest}
     */
    GetDocLinkRequest,

    /**
     * The GetDocLinkResponse model constructor.
     * @property {module:model/GetDocLinkResponse}
     */
    GetDocLinkResponse,

    /**
     * The GetDocStatusRequest model constructor.
     * @property {module:model/GetDocStatusRequest}
     */
    GetDocStatusRequest,

    /**
     * The GetDocStatusResponse model constructor.
     * @property {module:model/GetDocStatusResponse}
     */
    GetDocStatusResponse,

    /**
     * The GetDocumentAuditRequest model constructor.
     * @property {module:model/GetDocumentAuditRequest}
     */
    GetDocumentAuditRequest,

    /**
     * The GetDocumentAuditResponse model constructor.
     * @property {module:model/GetDocumentAuditResponse}
     */
    GetDocumentAuditResponse,

    /**
     * The GetDocumentAuditResponseActivityField model constructor.
     * @property {module:model/GetDocumentAuditResponseActivityField}
     */
    GetDocumentAuditResponseActivityField,

    /**
     * The GetDocumentPrepperLinkRequest model constructor.
     * @property {module:model/GetDocumentPrepperLinkRequest}
     */
    GetDocumentPrepperLinkRequest,

    /**
     * The GetDocumentPrepperLinkResponse model constructor.
     * @property {module:model/GetDocumentPrepperLinkResponse}
     */
    GetDocumentPrepperLinkResponse,

    /**
     * The GetDocumentRequest model constructor.
     * @property {module:model/GetDocumentRequest}
     */
    GetDocumentRequest,

    /**
     * The GetDocumentResponse model constructor.
     * @property {module:model/GetDocumentResponse}
     */
    GetDocumentResponse,

    /**
     * The GetDocumentTagFieldBoxPositionRequest model constructor.
     * @property {module:model/GetDocumentTagFieldBoxPositionRequest}
     */
    GetDocumentTagFieldBoxPositionRequest,

    /**
     * The GetDocumentTagFieldBoxPositionResponse model constructor.
     * @property {module:model/GetDocumentTagFieldBoxPositionResponse}
     */
    GetDocumentTagFieldBoxPositionResponse,

    /**
     * The GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField model constructor.
     * @property {module:model/GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField}
     */
    GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField,

    /**
     * The GetDocumentTagFieldPositionRequest model constructor.
     * @property {module:model/GetDocumentTagFieldPositionRequest}
     */
    GetDocumentTagFieldPositionRequest,

    /**
     * The GetDocumentTagFieldPositionResponse model constructor.
     * @property {module:model/GetDocumentTagFieldPositionResponse}
     */
    GetDocumentTagFieldPositionResponse,

    /**
     * The GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField model constructor.
     * @property {module:model/GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField}
     */
    GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField,

    /**
     * The GetPrepperTemplateListRequest model constructor.
     * @property {module:model/GetPrepperTemplateListRequest}
     */
    GetPrepperTemplateListRequest,

    /**
     * The GetPrepperTemplateListResponse model constructor.
     * @property {module:model/GetPrepperTemplateListResponse}
     */
    GetPrepperTemplateListResponse,

    /**
     * The GetPrepperTemplateListResponseTemplateInformationValuesField model constructor.
     * @property {module:model/GetPrepperTemplateListResponseTemplateInformationValuesField}
     */
    GetPrepperTemplateListResponseTemplateInformationValuesField,

    /**
     * The GetPrepperTemplateRequest model constructor.
     * @property {module:model/GetPrepperTemplateRequest}
     */
    GetPrepperTemplateRequest,

    /**
     * The GetPrepperTemplateResponse model constructor.
     * @property {module:model/GetPrepperTemplateResponse}
     */
    GetPrepperTemplateResponse,

    /**
     * The GetPrepperTemplateResponsePrepperTemplateValuesField model constructor.
     * @property {module:model/GetPrepperTemplateResponsePrepperTemplateValuesField}
     */
    GetPrepperTemplateResponsePrepperTemplateValuesField,

    /**
     * The InitiateFlowNoEmailRequest model constructor.
     * @property {module:model/InitiateFlowNoEmailRequest}
     */
    InitiateFlowNoEmailRequest,

    /**
     * The InitiateFlowNoEmailResponse model constructor.
     * @property {module:model/InitiateFlowNoEmailResponse}
     */
    InitiateFlowNoEmailResponse,

    /**
     * The InitiateFlowNoInitialEmailRequest model constructor.
     * @property {module:model/InitiateFlowNoInitialEmailRequest}
     */
    InitiateFlowNoInitialEmailRequest,

    /**
     * The InitiateFlowNoInitialEmailResponse model constructor.
     * @property {module:model/InitiateFlowNoInitialEmailResponse}
     */
    InitiateFlowNoInitialEmailResponse,

    /**
     * The InitiateFlowRequest model constructor.
     * @property {module:model/InitiateFlowRequest}
     */
    InitiateFlowRequest,

    /**
     * The InitiateFlowResponse model constructor.
     * @property {module:model/InitiateFlowResponse}
     */
    InitiateFlowResponse,

    /**
     * The LinkToPortfolioRequest model constructor.
     * @property {module:model/LinkToPortfolioRequest}
     */
    LinkToPortfolioRequest,

    /**
     * The LinkToPortfolioResponse model constructor.
     * @property {module:model/LinkToPortfolioResponse}
     */
    LinkToPortfolioResponse,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginResponse model constructor.
     * @property {module:model/LoginResponse}
     */
    LoginResponse,

    /**
     * The LogoutRequest model constructor.
     * @property {module:model/LogoutRequest}
     */
    LogoutRequest,

    /**
     * The LogoutResponse model constructor.
     * @property {module:model/LogoutResponse}
     */
    LogoutResponse,

    /**
     * The MultipleSignersSigningCeremonyRequest model constructor.
     * @property {module:model/MultipleSignersSigningCeremonyRequest}
     */
    MultipleSignersSigningCeremonyRequest,

    /**
     * The MultipleSignersSigningCeremonyRequestSignerListField model constructor.
     * @property {module:model/MultipleSignersSigningCeremonyRequestSignerListField}
     */
    MultipleSignersSigningCeremonyRequestSignerListField,

    /**
     * The MultipleSignersSigningCeremonyResponse model constructor.
     * @property {module:model/MultipleSignersSigningCeremonyResponse}
     */
    MultipleSignersSigningCeremonyResponse,

    /**
     * The Priority model constructor.
     * @property {module:model/Priority}
     */
    Priority,

    /**
     * The ProxyAllowedField model constructor.
     * @property {module:model/ProxyAllowedField}
     */
    ProxyAllowedField,

    /**
     * The SetDocumentOrderRequest model constructor.
     * @property {module:model/SetDocumentOrderRequest}
     */
    SetDocumentOrderRequest,

    /**
     * The SetDocumentOrderResponse model constructor.
     * @property {module:model/SetDocumentOrderResponse}
     */
    SetDocumentOrderResponse,

    /**
     * The SharePortfolioNoEmailRequest model constructor.
     * @property {module:model/SharePortfolioNoEmailRequest}
     */
    SharePortfolioNoEmailRequest,

    /**
     * The SharePortfolioNoEmailResponse model constructor.
     * @property {module:model/SharePortfolioNoEmailResponse}
     */
    SharePortfolioNoEmailResponse,

    /**
     * The SharePortfolioRequest model constructor.
     * @property {module:model/SharePortfolioRequest}
     */
    SharePortfolioRequest,

    /**
     * The SharePortfolioResponse model constructor.
     * @property {module:model/SharePortfolioResponse}
     */
    SharePortfolioResponse,

    /**
     * The SigningCeremonyV2Request model constructor.
     * @property {module:model/SigningCeremonyV2Request}
     */
    SigningCeremonyV2Request,

    /**
     * The SigningCeremonyV2Response model constructor.
     * @property {module:model/SigningCeremonyV2Response}
     */
    SigningCeremonyV2Response,

    /**
     * The TokenExtendRequest model constructor.
     * @property {module:model/TokenExtendRequest}
     */
    TokenExtendRequest,

    /**
     * The TokenExtendResponse model constructor.
     * @property {module:model/TokenExtendResponse}
     */
    TokenExtendResponse,

    /**
     * The TokenField model constructor.
     * @property {module:model/TokenField}
     */
    TokenField,

    /**
     * The TokenValidateRequest model constructor.
     * @property {module:model/TokenValidateRequest}
     */
    TokenValidateRequest,

    /**
     * The TokenValidateResponse model constructor.
     * @property {module:model/TokenValidateResponse}
     */
    TokenValidateResponse,

    /**
     * The WorkflowSignRequest model constructor.
     * @property {module:model/WorkflowSignRequest}
     */
    WorkflowSignRequest,

    /**
     * The WorkflowSignResponse model constructor.
     * @property {module:model/WorkflowSignResponse}
     */
    WorkflowSignResponse,

    /**
    * The AuditsApi service constructor.
    * @property {module:api/AuditsApi}
    */
    AuditsApi,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The PortfoliosApi service constructor.
    * @property {module:api/PortfoliosApi}
    */
    PortfoliosApi,

    /**
    * The SigningCeremonyApi service constructor.
    * @property {module:api/SigningCeremonyApi}
    */
    SigningCeremonyApi,

    /**
    * The TemplatesApi service constructor.
    * @property {module:api/TemplatesApi}
    */
    TemplatesApi,

    /**
    * The ViewersApi service constructor.
    * @property {module:api/ViewersApi}
    */
    ViewersApi,

    /**
    * The WorkFlowApi service constructor.
    * @property {module:api/WorkFlowApi}
    */
    WorkFlowApi
};
