/**
 * SigniFlow OpenAPI Spec v1
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SigniFlowConnect);
  }
}(this, function(expect, SigniFlowConnect) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SigniFlowConnect.PortfoliosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PortfoliosApi', function() {
    describe('postCreatePortfolio', function() {
      it('should call postCreatePortfolio successfully', function(done) {
        //uncomment below and update the code to test postCreatePortfolio
        //instance.postCreatePortfolio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postDownloadPortfolio', function() {
      it('should call postDownloadPortfolio successfully', function(done) {
        //uncomment below and update the code to test postDownloadPortfolio
        //instance.postDownloadPortfolio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postLinkToPortfolio', function() {
      it('should call postLinkToPortfolio successfully', function(done) {
        //uncomment below and update the code to test postLinkToPortfolio
        //instance.postLinkToPortfolio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postSetDocumentOrder', function() {
      it('should call postSetDocumentOrder successfully', function(done) {
        //uncomment below and update the code to test postSetDocumentOrder
        //instance.postSetDocumentOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postSharePortfolio', function() {
      it('should call postSharePortfolio successfully', function(done) {
        //uncomment below and update the code to test postSharePortfolio
        //instance.postSharePortfolio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postSharePortfolioNoEmail', function() {
      it('should call postSharePortfolioNoEmail successfully', function(done) {
        //uncomment below and update the code to test postSharePortfolioNoEmail
        //instance.postSharePortfolioNoEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
